<template>
  <div class="idmp-page dashboard-management">
    <PageHeader title="指标看板"><template #actions><el-button type="primary" @click="openCreate">+ 新建看板</el-button></template></PageHeader>
    <section class="toolbar"><el-input v-model="search" placeholder="搜索看板名称" clearable /><el-radio-group v-model="type"><el-radio-button label="">全部</el-radio-button><el-radio-button v-for="item in typeOptions" :key="item.value" :label="item.value">{{ item.label }}</el-radio-button></el-radio-group></section>
    <section v-if="filtered.length" class="dashboard-cards"><article v-for="item in filtered" :key="item.id" class="dashboard-card"><header><h2>{{ item.name }}</h2><el-tag size="small">{{ typeLabel(item.dashboardType) }}</el-tag></header><p>{{ item.description || '暂无描述' }}</p><dl><div><dt>分类</dt><dd>{{ item.category || '未分类' }}</dd></div><div><dt>适用范围</dt><dd>{{ scopeLabel(item.scope) }}</dd></div><div><dt>更新时间</dt><dd>{{ formatDate(item.updatedAt) }}</dd></div></dl><footer><el-button type="primary" @click="open(item.id)">打开</el-button><el-button @click="copy(item.id)">复制</el-button><el-dropdown @command="command => menu(command, item)"><el-button>···</el-button><template #dropdown><el-dropdown-menu><el-dropdown-item command="rename">重命名</el-dropdown-item><el-dropdown-item command="delete" :disabled="protectedIds.has(item.id)">删除</el-dropdown-item></el-dropdown-menu></template></el-dropdown></footer></article></section>
    <StatePanel v-else type="empty" title="还没有自定义看板" description="创建一个看板，自由组合指标与图表。"><template #actions><el-button type="primary" @click="openCreate">新建看板</el-button></template></StatePanel>
    <el-dialog v-model="creating" title="新建看板" width="520px" destroy-on-close><el-form label-position="top"><el-form-item label="名称 *"><el-input v-model="form.name" /></el-form-item><el-form-item label="描述"><el-input v-model="form.description" type="textarea" /></el-form-item><el-form-item label="类型 *"><el-select v-model="form.dashboardType"><el-option v-for="item in typeOptions" :key="item.value" :label="item.label" :value="item.value" /></el-select></el-form-item><el-form-item label="分类"><el-input v-model="form.category" /></el-form-item><el-form-item label="适用范围 *"><el-select v-model="form.scope"><el-option label="全院" value="hospital" /><el-option label="科室" value="department" /><el-option label="个人" value="personal" /></el-select></el-form-item><el-form-item label="创建方式"><el-radio-group v-model="form.mode"><el-radio label="blank">空白看板</el-radio><el-radio label="template">使用模板</el-radio></el-radio-group></el-form-item><el-form-item v-if="form.mode === 'template'" label="布局模板"><el-select v-model="form.templateId"><el-option v-for="item in templates" :key="item.id" :label="item.name" :value="item.id" /></el-select></el-form-item></el-form><template #footer><el-button @click="creating = false">取消</el-button><el-button type="primary" :disabled="!form.name.trim()" @click="create">创建并打开</el-button></template></el-dialog>
  </div>
</template>
<script setup>
import { computed, ref } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import PageHeader from '@/idmp/components/PageHeader.vue'
import StatePanel from '@/idmp/components/StatePanel.vue'
import { BUILT_IN_LAYOUT_TEMPLATES, readLocalLayoutTemplates } from '@/idmp/features/dashboard/layoutTemplates.js'
import { BUILT_IN_DASHBOARD_IDS, createLocalDashboard, duplicateLocalDashboard, readDashboardCatalog, removeLocalDashboard, renameLocalDashboard } from '@/idmp/features/dashboard/catalog.js'
const router = useRouter(), search = ref(''), type = ref(''), creating = ref(false), catalog = ref([]), protectedIds = BUILT_IN_DASHBOARD_IDS
const typeOptions = [{ value: 'hospital-overview', label: '全院概览' }, { value: 'topic', label: '专题' }, { value: 'scene', label: '场景' }, { value: 'department', label: '科室' }, { value: 'custom', label: '自定义' }]
const form = ref({ name: '', description: '', dashboardType: 'custom', category: '', scope: 'personal', mode: 'blank', templateId: 'builtin-hospital-overview' })
const templates = computed(() => [...BUILT_IN_LAYOUT_TEMPLATES, ...readLocalLayoutTemplates(localStorage)])
const filtered = computed(() => catalog.value.filter(item => (!type.value || item.dashboardType === type.value) && item.name.includes(search.value.trim())))
function refresh() { catalog.value = readDashboardCatalog(localStorage).sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)) }
function openCreate() { form.value = { name: '', description: '', dashboardType: 'custom', category: '', scope: 'personal', mode: 'blank', templateId: templates.value[0]?.id || '' }; creating.value = true }
function open(id) { router.push({ name: 'Dashboard', query: { id } }) }
function create() { try { const template = form.value.mode === 'template' ? templates.value.find(item => item.id === form.value.templateId) : null; const schema = createLocalDashboard(form.value, { template, storage: localStorage }); creating.value = false; refresh(); open(schema.id) } catch (error) { ElMessage.error(error.message || '创建看板失败') } }
function copy(id) { try { const schema = duplicateLocalDashboard(id, localStorage); refresh(); ElMessage.success('已创建副本'); open(schema.id) } catch (error) { ElMessage.error(error.message || '复制失败') } }
async function menu(command, item) { if (command === 'rename') { const { value } = await ElMessageBox.prompt('请输入新名称', '重命名看板', { inputValue: item.name, inputValidator: value => String(value || '').trim() ? true : '名称不能为空' }); renameLocalDashboard(item.id, value, localStorage); refresh(); ElMessage.success('已重命名') } if (command === 'delete') { try { await ElMessageBox.confirm(`确认删除“${item.name}”？删除后，本地保存的布局和配置也会一起删除。`, '删除看板', { type: 'warning', confirmButtonText: '删除', cancelButtonText: '取消' }); removeLocalDashboard(item.id, localStorage); refresh(); ElMessage.success('已删除') } catch (error) { if (error?.message && error !== 'cancel' && error !== 'close') ElMessage.error(error.message) } } }
function typeLabel(value) { return typeOptions.find(item => item.value === value)?.label || value }
function scopeLabel(value) { return ({ hospital: '全院', department: '科室', personal: '个人' })[value] || value }
function formatDate(value) { return value ? new Intl.DateTimeFormat('zh-CN', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '—' }
refresh()
</script>
<style scoped>.toolbar{display:flex;gap:16px;justify-content:space-between;margin-bottom:20px}.toolbar .el-input{max-width:280px}.dashboard-cards{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:16px}.dashboard-card{padding:18px;border:1px solid #e3e9eb;border-radius:10px;background:#fff;box-shadow:0 1px 2px #1018280a}.dashboard-card header,.dashboard-card footer{display:flex;align-items:center;justify-content:space-between;gap:8px}.dashboard-card h2{margin:0;font-size:16px}.dashboard-card p{min-height:36px;color:#667085;font-size:13px}.dashboard-card dl{display:grid;grid-template-columns:repeat(2,1fr);gap:10px;margin:16px 0}.dashboard-card dt{font-size:11px;color:#98a2b3}.dashboard-card dd{margin:3px 0 0;font-size:12px;color:#344054}.dashboard-card dl div:last-child{grid-column:span 2}@media(max-width:720px){.toolbar{align-items:stretch;flex-direction:column}.toolbar .el-input{max-width:none}}</style>
