<template>
  <div class="idmp-page instantiate-page">
    <PageHeader title="从模板创建因子" status="PUBLISHED" status-label="已发布模板"><template #actions><el-button @click="router.push('/factor/templates')">返回模板目录</el-button></template></PageHeader>
    <section v-loading="loading.page" class="surface-card wizard-card">
      <template v-if="!loadError">
        <el-steps :active="workflowActive" finish-status="success" simple class="wizard-steps"><el-step title="填写实例信息" /><el-step title="创建因子草稿" /><el-step title="编译校验" /><el-step title="试算验证（可选）" /><el-step title="发布版本" /></el-steps>
        <div class="template-summary"><div><span>模板</span><strong>{{ template.name || template.code || '-' }}</strong></div><div><span>版本</span><strong>V{{ version.versionNo || '-' }}</strong></div><div><span>适用数据域</span><strong>{{ domainSummary }}</strong></div></div>
        <el-alert type="info" :closable="false" show-icon title="计算口径由模板固定。创建草稿后将在本页继续编译、可选试算和发布。" />
        <el-form ref="formRef" :model="form" :rules="formRules" label-position="top" class="instantiate-form" :disabled="Boolean(createdFactor)">
          <div class="section-title"><span>1</span><div><h2>因子基本信息</h2><p>填写本次实例的业务标识。</p></div></div>
          <div class="form-grid"><el-form-item label="因子编码" prop="factorCode"><el-input v-model.trim="form.factorCode" placeholder="例如 DISCHARGE_FEMALE_COUNT" /></el-form-item><el-form-item label="因子名称" prop="factorName"><el-input v-model.trim="form.factorName" placeholder="例如 女性出院病案人次" /></el-form-item><el-form-item label="业务分类"><el-input v-model.trim="form.category" placeholder="例如 医疗质量" /></el-form-item></div>
          <el-form-item label="说明"><el-input v-model.trim="form.description" type="textarea" :rows="2" placeholder="可选：说明本次实例的业务用途" /></el-form-item>
          <el-divider />
          <div class="section-title"><span>2</span><div><h2>模板预留参数</h2><p>仅显示模板声明并允许业务用户填写的参数。</p></div></div>
          <el-empty v-if="!parameterFields.length" description="该模板没有可填写的预留参数，将按固定口径创建。" :image-size="64" />
          <div v-else class="parameter-grid"><el-form-item v-for="field in parameterFields" :key="field.code" :label="field.label" :required="field.required"><el-select v-if="field.enumValues.length" v-model="parameterValues[field.code]" filterable placeholder="请选择标准值"><el-option v-for="option in field.enumValues" :key="String(option)" :label="optionLabel(field, option)" :value="option" /></el-select><el-input-number v-else-if="field.type === 'number' || field.type === 'integer'" v-model="parameterValues[field.code]" :precision="field.type === 'integer' ? 0 : undefined" :step="field.type === 'integer' ? 1 : 0.1" /><el-switch v-else-if="field.type === 'boolean'" v-model="parameterValues[field.code]" /><el-input v-else v-model="parameterValues[field.code]" :placeholder="field.placeholder" /><div v-if="field.description || field.defaultValue !== undefined" class="field-help">{{ field.description || `默认值：${formatValue(field.defaultValue)}` }}</div></el-form-item></div>
          <el-divider />
          <div class="section-title"><span>3</span><div><h2>创建确认</h2><p>确认后，模板参数会替换为该因子的最终 DSL。</p></div></div>
          <div class="confirmation-list"><div v-for="field in parameterFields" :key="field.code"><span>{{ field.label }}</span><strong>{{ formatValue(parameterValues[field.code]) }}</strong></div><div v-if="!parameterFields.length"><span>模板参数</span><strong>无，按模板固定口径创建</strong></div></div>
          <div v-if="!createdFactor" class="actions"><el-button type="primary" :loading="submitting" @click="instantiate">创建因子草稿</el-button></div>
        </el-form>
        <section v-if="createdFactor" ref="workflowSection" class="workflow-panel">
          <el-alert type="success" :closable="false" show-icon title="因子草稿已创建，请继续编译校验。" />
          <div class="section-title"><span>4</span><div><h2>编译、试算与发布</h2><p>编译通过后即可发布；试算仅用于验证某个时间范围内的实际计算结果。</p></div></div>
          <div class="workflow-identity"><div><span>因子 ID</span><strong>{{ workflow.factorId }}</strong></div><div><span>草稿版本 ID</span><strong>{{ workflow.versionId }}</strong></div><div><span>编译产物</span><strong>{{ workflow.artifactId || '-' }}</strong></div><div><span>当前状态</span><strong>{{ workflow.status || 'DRAFT' }}</strong></div></div>
          <el-steps :active="workflowProgress" finish-status="success" simple class="workflow-steps"><el-step title="创建草稿" /><el-step title="编译校验" /><el-step title="试算验证（可选）" /><el-step title="发布版本" /></el-steps>
          <div class="workflow-actions"><el-button type="primary" :loading="loading.compile" :disabled="workflow.published" @click="compileCurrentVersion">编译并校验</el-button><el-button :disabled="!workflow.compiled || workflow.published" @click="showTrial = !showTrial">{{ showTrial ? '收起试算验证' : '可选：试算验证' }}</el-button><el-button type="success" :loading="loading.publish" :disabled="!canPublish" @click="publishCurrentVersion">发布因子版本</el-button></div>
          <div v-if="showTrial" class="trial-card"><div><strong>试算验证（可选）</strong><small>试算不会修改因子定义；所选时间仅决定本次用哪段实际数据验证结果。</small></div><el-date-picker v-model="trialPeriod" type="datetimerange" value-format="YYYY-MM-DDTHH:mm:ss" start-placeholder="开始时间" end-placeholder="结束时间" /><el-button :loading="loading.trial || loading.result" @click="trialCurrentVersion">{{ trialButtonLabel }}</el-button></div>
          <div v-if="workflow.taskId" class="workflow-feedback"><span>任务 ID：{{ workflow.taskId }}</span><span>任务状态：{{ workflow.taskStatus || 'QUEUED' }}</span><el-button v-if="!isTerminalTask" link type="primary" :loading="loading.status" @click="refreshTrialStatus">刷新状态</el-button></div>
          <el-alert v-if="workflow.message" :title="workflow.message" :type="workflow.messageType" :closable="false" show-icon class="workflow-alert" />
          <div v-if="trialRows.length" class="trial-results"><div class="result-head"><h3>试算结果</h3><span>共 {{ trialRows.length }} 条</span></div><el-table :data="trialRows" size="small" border><el-table-column type="index" label="#" width="54" /><el-table-column label="维度" min-width="220"><template #default="{ row }">{{ formatDimensions(row) }}</template></el-table-column><el-table-column label="结果值" min-width="130"><template #default="{ row }">{{ resultValue(row) }}</template></el-table-column><el-table-column prop="qualityStatus" label="质量状态" width="120" /></el-table></div>
          <div v-if="workflow.published" class="published-next"><strong>因子版本已发布，可供指标引用。</strong><el-button type="primary" @click="router.push('/factor')">返回因子目录</el-button></div>
        </section>
      </template>
      <el-result v-else icon="error" title="无法读取可用模板参数" :sub-title="loadError"><template #extra><el-button type="primary" @click="load">重试</el-button></template></el-result>
    </section>
  </div>
</template>

<script setup>
import { computed, nextTick, onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { useRoute, useRouter } from 'vue-router'
import PageHeader from '@/idmp/components/PageHeader.vue'
import { compileFactorVersion, fetchFactorTemplateParameterSchema, fetchFactorTemplateVersion, fetchFactorTrialResults, instantiateFactorTemplateVersion, publishFactorVersion, trialFactorVersion } from '@/idmp/api/modules/factors'
import { fetchAsyncTask } from '@/idmp/api/modules/calculation'

const route = useRoute(); const router = useRouter(); const formRef = ref(); const workflowSection = ref(); const loading = reactive({ page: false, compile: false, trial: false, result: false, publish: false, status: false }); const submitting = ref(false); const loadError = ref(''); const template = reactive({}); const version = reactive({}); const parameterFields = ref([]); const parameterValues = reactive({}); const createdFactor = ref(null); const showTrial = ref(false); const trialPeriod = ref([]); const trialRows = ref([]); const workflow = reactive({ factorId: '', versionId: '', status: 'DRAFT', artifactId: '', compiled: false, published: false, taskId: '', batchId: '', taskStatus: '', qualityStatus: '', resultsLoaded: false, message: '', messageType: 'info' }); const form = reactive({ factorCode: '', factorName: '', description: '', category: '' })
const formRules = { factorCode: [{ required: true, message: '请输入因子编码', trigger: 'blur' }, { pattern: /^[A-Z][A-Z0-9_]{0,63}$/, message: '使用大写字母开头，仅含大写字母、数字和下划线，最多 64 位', trigger: 'blur' }], factorName: [{ required: true, message: '请输入因子名称', trigger: 'blur' }] }
const domainSummary = computed(() => (version.applicableDomains || version.templateDefinition?.applicableDomains || []).map(item => item.domainName || item.domainCode || item.code).filter(Boolean).join('、') || '-')
const workflowActive = computed(() => workflow.published ? 5 : workflow.compiled ? 3 : createdFactor.value ? 2 : 1); const workflowProgress = computed(() => workflow.published ? 4 : workflow.resultsLoaded ? 3 : workflow.compiled ? 2 : 1); const isTerminalTask = computed(() => ['SUCCEEDED', 'SUCCESS', 'FAILED', 'CANCELED', 'CANCELLED', 'PARTIAL_SUCCEEDED'].includes(String(workflow.taskStatus).toUpperCase())); const canPublish = computed(() => workflow.compiled && !workflow.published && !loading.publish); const trialButtonLabel = computed(() => loading.trial || loading.result ? '正在试算并读取结果' : workflow.resultsLoaded ? '重新试算并查看结果' : workflow.taskId && !isTerminalTask.value ? '继续查询试算状态' : '试算并查看结果')
onMounted(load)
async function load() { loading.page = true; loadError.value = ''; try { const [schemaResponse, detail] = await Promise.all([fetchFactorTemplateParameterSchema(route.params.templateId), fetchFactorTemplateVersion(route.params.versionId)]); Object.assign(template, detail?.template || {}); Object.assign(version, detail?.version || detail || {}); const schema = schemaResponse?.schema || schemaResponse || {}; const metadata = schemaResponse?.parameters || version.parameters || []; parameterFields.value = buildFields(schema, metadata); parameterFields.value.forEach(field => { if (!(field.code in parameterValues)) parameterValues[field.code] = field.defaultValue ?? (field.type === 'boolean' ? false : '') }) } catch (error) { loadError.value = error?.message || '模板参数读取失败，请确认模板已发布且当前账号有使用权限。' } finally { loading.page = false } }
function buildFields(schema, metadata) { const required = new Set(schema.required || []); return Object.entries(schema.properties || {}).map(([code, definition]) => { const meta = metadata.find(item => item.code === code) || {}; return { code, label: definition.title || meta.displayName || code, description: definition.description || meta.description || '', type: definition.type || meta.dataType?.toLowerCase() || 'string', enumValues: Array.isArray(definition.enum) ? definition.enum : Array.isArray(meta.validation?.enum) ? meta.validation.enum : [], defaultValue: definition.default ?? meta.defaultValue, required: required.has(code) || meta.required === true, options: meta.options || [], placeholder: definition.placeholder || `请输入${definition.title || meta.displayName || code}` } }) }
function optionLabel(field, option) { const match = field.options.find(item => (item.value || item.code) === option); return match ? `${match.label || match.name || option}（${option}）` : String(option) } function formatValue(value) { return value === undefined || value === null || value === '' ? '未填写' : Array.isArray(value) ? value.join('、') : String(value) } function toId(value) { return value === undefined || value === null ? '' : String(value) }
async function instantiate() { if (!(await formRef.value?.validate().catch(() => false))) return; const missing = parameterFields.value.find(field => field.required && (parameterValues[field.code] === undefined || parameterValues[field.code] === null || parameterValues[field.code] === '')); if (missing) return ElMessage.warning(`请填写参数：${missing.label}`); submitting.value = true; try { const result = await instantiateFactorTemplateVersion(route.params.versionId, { factorCode: form.factorCode, factorName: form.factorName, description: form.description || undefined, category: form.category || undefined, parameterValues: Object.fromEntries(parameterFields.value.map(field => [field.code, parameterValues[field.code]])) }); const factor = result?.factor || result; if (!factor?.id || !(factor.draftVersionId || factor.versionId)) throw new Error('实例化成功但未返回因子草稿版本，无法继续编译'); createdFactor.value = factor; workflow.factorId = toId(factor.id); workflow.versionId = toId(factor.draftVersionId || factor.versionId); workflow.status = factor.status || 'DRAFT'; workflow.message = '因子草稿已创建。下一步请执行编译校验。'; workflow.messageType = 'success'; ElMessage.success('因子草稿已创建'); await nextTick(); workflowSection.value?.scrollIntoView({ behavior: 'smooth', block: 'start' }) } catch (error) { ElMessage.error(error?.message || '因子草稿创建失败') } finally { submitting.value = false } }
async function compileCurrentVersion() { if (!workflow.versionId || loading.compile) return; loading.compile = true; try { const result = await compileFactorVersion(workflow.versionId, {}); workflow.artifactId = toId(result?.artifactId || result?.id || result?.compileArtifactId); const status = String(result?.status || result?.compileStatus || '').toUpperCase(); workflow.compiled = ['VALID', 'VALIDATED', 'SUCCEEDED', 'SUCCESS'].includes(status); workflow.message = workflow.compiled ? `编译校验通过${workflow.artifactId ? `，产物 ID：${workflow.artifactId}` : ''}。现在可以发布；也可选做试算验证。` : `编译未通过：${formatDiagnostics(result?.diagnostics) || status || '请查看后端诊断信息'}`; workflow.messageType = workflow.compiled ? 'success' : 'warning'; workflow.status = workflow.compiled ? 'VALID' : workflow.status; if (workflow.compiled) ElMessage.success('编译校验通过'); else ElMessage.warning(workflow.message) } catch (error) { workflow.compiled = false; workflow.message = error?.message || '因子编译失败'; workflow.messageType = 'error'; ElMessage.error(workflow.message) } finally { loading.compile = false } }
async function trialCurrentVersion() { if (!workflow.compiled || loading.trial || loading.result) return; if (workflow.taskId && !isTerminalTask.value) return refreshTrialStatus(); if (workflow.taskStatus === 'SUCCEEDED' && workflow.batchId && !workflow.resultsLoaded) return loadTrialResults(); if (!Array.isArray(trialPeriod.value) || trialPeriod.value.length !== 2) return ElMessage.warning('试算验证需要选择完整时间范围；该范围仅用于本次实际数据验证。'); loading.trial = true; trialRows.value = []; workflow.resultsLoaded = false; try { const accepted = await trialFactorVersion(workflow.versionId, { periodStart: trialPeriod.value[0], periodEnd: trialPeriod.value[1] }, `factor-trial-${workflow.versionId}-${Date.now()}`); workflow.taskId = toId(accepted?.taskId || accepted?.asyncTaskId); workflow.batchId = toId(accepted?.batchId); workflow.taskStatus = String(accepted?.status || 'QUEUED').toUpperCase(); workflow.message = `试算任务已提交，批次 ID：${workflow.batchId || '-'}。`; workflow.messageType = 'info'; if (workflow.taskId) await pollTrialTask(); if (['SUCCEEDED', 'SUCCESS'].includes(workflow.taskStatus)) await loadTrialResults() } catch (error) { workflow.message = error?.message || '试算提交失败'; workflow.messageType = 'error'; ElMessage.error(workflow.message) } finally { loading.trial = false } }
async function pollTrialTask() { for (let index = 0; index < 15; index += 1) { const task = await fetchAsyncTask(workflow.taskId); workflow.taskStatus = String(task?.status || workflow.taskStatus).toUpperCase(); workflow.batchId = toId(task?.batchId || workflow.batchId); if (isTerminalTask.value) break; await new Promise(resolve => setTimeout(resolve, 2000)) } }
async function refreshTrialStatus() { if (!workflow.taskId || loading.status) return; loading.status = true; try { const task = await fetchAsyncTask(workflow.taskId); workflow.taskStatus = String(task?.status || workflow.taskStatus).toUpperCase(); workflow.batchId = toId(task?.batchId || workflow.batchId); if (['SUCCEEDED', 'SUCCESS'].includes(workflow.taskStatus)) await loadTrialResults() } catch (error) { ElMessage.error(error?.message || '试算任务状态查询失败') } finally { loading.status = false } }
async function loadTrialResults() { if (!workflow.versionId || !workflow.batchId || loading.result) return; loading.result = true; try { const result = await fetchFactorTrialResults(workflow.versionId, workflow.batchId, 1, 100); const payload = result?.data || result || {}; trialRows.value = payload?.results?.records || payload?.records || []; workflow.resultsLoaded = String(payload?.batchStatus || payload?.status || 'SUCCEEDED').toUpperCase() === 'SUCCEEDED'; workflow.qualityStatus = payload?.qualityStatus || ''; workflow.message = trialRows.value.length ? `试算完成，共 ${trialRows.value.length} 条结果。` : '试算完成：该时间范围内没有匹配源数据。'; workflow.messageType = 'success' } catch (error) { workflow.message = error?.message || '试算结果读取失败'; workflow.messageType = 'error'; ElMessage.error(workflow.message) } finally { loading.result = false } }
async function publishCurrentVersion() { if (!canPublish.value) return; try { await ElMessageBox.confirm(`确认发布因子版本 ${workflow.versionId}？`, '发布因子版本', { type: 'warning' }) } catch { return } loading.publish = true; try { const result = await publishFactorVersion(workflow.versionId); workflow.status = result?.status || result?.publicationStatus || 'PUBLISHED'; workflow.published = true; workflow.message = `因子版本 ${workflow.versionId} 已发布，可供指标引用。`; workflow.messageType = 'success'; ElMessage.success('因子版本已发布') } catch (error) { workflow.message = error?.message || '因子版本发布失败'; workflow.messageType = 'error'; ElMessage.error(workflow.message) } finally { loading.publish = false } }
function formatDiagnostics(diagnostics) { return (diagnostics || []).map(item => item.message || item.code).filter(Boolean).join('；') } function formatDimensions(row) { const dimensions = row?.dimensions || row?.dimensionValues || {}; return Object.keys(dimensions).length ? Object.entries(dimensions).map(([key, value]) => `${key}=${value}`).join('，') : '总体' } function resultValue(row) { return row?.displayValue ?? row?.valueDecimal ?? row?.resultValue ?? row?.value ?? '-' }
</script>

<style scoped lang="scss">
.wizard-card{padding:22px}.wizard-steps{margin-bottom:20px}.template-summary,.form-grid,.parameter-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px}.template-summary{margin-bottom:18px;padding:14px;background:#f7fbff;border:1px solid #d6ecff;border-radius:8px}.template-summary span,.template-summary strong{display:block}.template-summary span,.field-help{color:#8c8c8c;font-size:12px}.template-summary strong{margin-top:4px;color:#1677c2}.instantiate-form{margin-top:24px}.section-title{display:grid;grid-template-columns:28px minmax(0,1fr);column-gap:12px;align-items:start;margin:20px 0 14px}.section-title>span{display:flex;align-items:center;justify-content:center;width:28px;height:28px;line-height:28px;color:#fff;background:#1890ff;border-radius:50%;font-weight:600}.section-title h2{margin:2px 0 4px;font-size:16px;line-height:22px}.section-title p{margin:0;color:#8c8c8c;font-size:13px;line-height:20px}.field-help{margin-top:6px}.confirmation-list{display:grid;gap:8px;padding:14px;background:#fafafa;border-radius:6px}.confirmation-list>div{display:flex;justify-content:space-between;gap:16px}.confirmation-list span{color:#595959}.confirmation-list strong{color:#1677c2}.actions{margin-top:20px;text-align:right}.workflow-panel{margin-top:28px;padding-top:4px;border-top:3px solid #1890ff}.workflow-identity{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin-bottom:16px}.workflow-identity>div{padding:12px;background:#f7f8fa;border-radius:6px}.workflow-identity span,.workflow-identity strong{display:block}.workflow-identity span{margin-bottom:5px;color:#8c8c8c;font-size:12px}.workflow-identity strong{overflow:hidden;font-family:Consolas,monospace;text-overflow:ellipsis}.workflow-steps{margin-bottom:18px}.workflow-actions,.workflow-feedback,.published-next{display:flex;align-items:center;flex-wrap:wrap;gap:10px}.trial-card{display:grid;grid-template-columns:minmax(220px,1fr) minmax(280px,420px) auto;gap:12px;align-items:end;margin-top:16px;padding:14px;background:#f7fbff;border:1px solid #d6ecff;border-radius:8px}.trial-card strong,.trial-card small{display:block}.trial-card small{margin-top:4px;color:#6b7280}.workflow-feedback{margin-top:14px;padding:12px;background:#f7fbff;border-radius:6px;color:#595959}.workflow-alert{margin-top:14px}.trial-results{margin-top:18px}.result-head{display:flex;justify-content:space-between;margin-bottom:10px}.result-head h3{margin:0;font-size:15px}.published-next{margin-top:18px;padding:16px;background:#f6ffed;border:1px solid #b7eb8f;border-radius:8px}.published-next strong{margin-right:auto;color:#389e0d}@media(max-width:900px){.template-summary,.form-grid,.parameter-grid,.workflow-identity{grid-template-columns:1fr}.trial-card{grid-template-columns:1fr}}
</style>
