<template>
  <div class="idmp-page factor-editor">
  <PageHeader :title="pageTitle"><template #actions><el-button :icon="ArrowLeft" @click="router.push('/factor')">返回列表</el-button><el-button type="primary" :loading="loading.save" @click="saveFactor">{{ isCreate ? '保存因子' : '保存修改' }}</el-button></template></PageHeader>
  <section class="surface-card editor-section"><div class="section-title"><span>1</span><div><h2>基础信息</h2><p>填写业务人员识别因子所需的信息。</p></div></div><el-form ref="basicFormRef" :model="basicForm" :rules="basicRules" label-width="88px"><el-row :gutter="16"><el-col :xs="24" :md="8"><el-form-item label="因子编码" prop="code"><el-input v-model.trim="basicForm.code" :disabled="!isCreate" /></el-form-item></el-col><el-col :xs="24" :md="8"><el-form-item label="因子名称" prop="name"><el-input v-model.trim="basicForm.name" /></el-form-item></el-col><el-col :xs="24" :md="8"><el-form-item label="业务分类"><el-input v-model.trim="basicForm.category" placeholder="如：医疗质量" /></el-form-item></el-col><el-col :xs="24" :md="8"><el-form-item label="数据域"><el-select v-model="dslForm.domainCode" filterable :loading="loading.domains" @change="handleDomainChange"><el-option v-for="domain in domains" :key="domain.code" :label="domain.name" :value="domain.code" /></el-select></el-form-item></el-col></el-row><el-form-item label="描述"><el-input v-model.trim="basicForm.description" type="textarea" :rows="2" /></el-form-item></el-form></section>
    <section class="surface-card editor-section"><div class="section-title"><span>2</span><div><h2>统计对象</h2><p>选择业务数据域和语义表，页面只展示业务名称。</p></div></div><div class="business-summary"><span>数据域</span><strong>{{ currentDomainName }}</strong><small v-if="dslForm.tableCode">语义表：{{ currentTableName }}</small></div><el-form label-width="88px"><el-form-item label="语义表"><el-select v-model="dslForm.tableCode" filterable clearable @change="handleTableChange"><el-option v-for="table in tables" :key="table.code" :label="table.name" :value="table.code" /></el-select></el-form-item></el-form></section>
    <section class="surface-card editor-section"><div class="section-title"><span>3</span><div><h2>统计方式</h2><p>使用业务人员熟悉的统计方式，系统自动转换为 Factor DSL。</p></div></div><div class="measure-cards"><button v-for="item in aggregationOptions" :key="item.value" type="button" class="measure-card" :class="{active:dslForm.aggregation===item.value}" @click="selectAggregation(item.value)"><strong>{{ item.label }}</strong><span>{{ item.description }}</span></button></div><el-form v-if="dslForm.aggregation !== 'COUNT'" label-width="88px" class="measure-field"><el-form-item label="统计字段"><el-select v-model="dslForm.fieldCode" filterable clearable><el-option v-for="field in fields" :key="field.code" :label="fieldOptionLabel(field)" :value="field.code" /></el-select></el-form-item></el-form><el-form label-width="88px" class="group-by-form"><el-form-item label="分组维度"><el-select v-model="dslForm.groupBy" multiple collapse-tags filterable clearable><el-option v-for="field in fields" :key="field.code" :label="fieldOptionLabel(field)" :value="field.code" /></el-select></el-form-item></el-form></section>
    <section class="surface-card editor-section"><div class="section-title"><span>4</span><div><h2>统计范围</h2><p>配置“哪些患者/记录应该被统计”，不再局限于统计周期。</p></div></div><FactorRuleBuilder :model-value="filters" :fields="fields" @update="ruleVersion++" /><div class="rule-explanation"><strong>规则说明</strong><span>{{ ruleExplanation }}</span></div><div class="section-footer"><el-button link type="primary" @click="showDsl=true">查看技术配置</el-button></div></section>
    <section v-if="template.templateId" class="surface-card editor-section"><div class="section-title"><span>5</span><div><h2>模板参数</h2><p>模板参数仅作为业务输入，保存时由后端实例化为最终 DSL。</p></div></div><el-form label-position="top"><el-form-item v-for="item in parameters" :key="item.code" :label="item.displayName || item.code"><el-date-picker v-if="String(item.dataType || item.type).includes('DATETIME')" v-model="parameterValues[item.code]" type="datetimerange" value-format="YYYY-MM-DDTHH:mm:ss" /><el-select v-else-if="item.valueSourceType === 'ENUM' || item.valueSourceType === 'VALUE_SET'" v-model="parameterValues[item.code]" filterable><el-option v-for="option in item.options || []" :key="option.value || option.code || option" :label="option.label || option.name || option" :value="option.value || option.code || option" /></el-select><el-input v-else v-model="parameterValues[item.code]" /></el-form-item></el-form></section>
    <DslPreview v-model="showDsl" :dsl="currentDsl" />
  </div>
</template>
<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { ArrowLeft } from '@element-plus/icons-vue'
import PageHeader from '@/idmp/components/PageHeader.vue'
import FactorRuleBuilder from '@/idmp/components/FactorRuleBuilder.vue'
import DslPreview from '@/idmp/components/DslPreview.vue'
import { fetchDataDomains, fetchSemanticTableFields, fetchSemanticTables } from '@/idmp/api/modules/meta'
import { adaptDataDomainList, adaptSemanticFieldList, adaptSemanticTableList } from '@/idmp/api/adapters/meta'
import { createFactor, fetchFactor, fetchFactorTemplateParameterSchema, fetchFactorVersion, fetchFactorVersionsByFactor, instantiateFactorTemplateVersion, updateFactor } from '@/idmp/api/modules/factors'
import { normalizeSemanticField, fieldByCode } from '@/idmp/utils/semanticField'
import { buildFactorDsl, validateFilterNode } from '@/idmp/utils/dslBuilder'
const route=useRoute();const router=useRouter();const basicFormRef=ref();const showDsl=ref(false);const ruleVersion=ref(0);const isCreate=computed(()=>!route.params.id||route.params.id==='new');const pageTitle=computed(()=>isCreate.value?'因子编辑 / 新增因子':`因子编辑 / ${basicForm.name||route.params.id}`)
const basicForm=reactive({code:`FACTOR_${Date.now()}`,name:'',description:'',category:''});const dslForm=reactive({domainCode:'',tableCode:'',aggregation:'COUNT',fieldCode:'',groupBy:[]});const filters=reactive({nodeType:'AND',children:[]});const template=reactive({templateId:route.query.templateId||'',versionId:route.query.versionId||''});const parameters=ref([]);const parameterValues=reactive({});const domains=ref([]);const tables=ref([]);const fields=ref([]);const metadataRequestVersion=ref(0);const resourceVersion=ref(0);const loading=reactive({domains:false,template:false,save:false});
const aggregationOptions=[{value:'COUNT',label:'统计人数',description:'统计符合条件的患者或记录数量'},{value:'COUNT_DISTINCT',label:'统计次数',description:'按唯一业务对象去重后统计'},{value:'SUM',label:'统计金额',description:'汇总业务金额或数量字段'},{value:'AVG',label:'统计平均值',description:'计算业务字段平均值'}];const basicRules={code:[{required:true,message:'请输入因子编码',trigger:'blur'}],name:[{required:true,message:'请输入因子名称',trigger:'blur'}]};const currentDomainName=computed(()=>domains.value.find(x=>x.code===dslForm.domainCode)?.name||'未选择数据域');const currentTableName=computed(()=>tables.value.find(x=>x.code===dslForm.tableCode)?.name||dslForm.tableCode);const currentDsl=computed(()=>buildDsl());const ruleExplanation=computed(()=>{ruleVersion.value;return describeNode(filters)||'尚未配置统计范围，请添加至少一条条件'})
onMounted(async()=>{await loadDomains();if(template.templateId)await loadParameterSchema();if(!isCreate.value)await loadExisting()})
async function loadExisting(){try{const factor=await fetchFactor(route.params.id);basicForm.code=factor.code??factor.factorCode??basicForm.code;basicForm.name=factor.name??factor.factorName??'';basicForm.description=factor.description??'';basicForm.category=factor.category??'';resourceVersion.value=Number(factor.resourceVersion??factor.version??0);const version=await loadLatestFactorVersion(factor);const dsl=version?.dsl??factor.dsl??factor.factorDsl??factor.latestVersion?.dsl??{};dslForm.domainCode=dsl.primaryDomain?.domainCode??dsl.domainCode??dslForm.domainCode;dslForm.tableCode=dsl.primaryDomain?.semanticTableCode??'';dslForm.aggregation=dsl.aggregation?.function??'COUNT';dslForm.fieldCode=dsl.aggregation?.fieldCode??'';dslForm.groupBy=(dsl.groupBy||[]).map(x=>x.fieldCode||x);Object.assign(filters,dsl.filters||{nodeType:'AND',children:[]});await loadTables(true)}catch(e){ElMessage.warning(e?.message||'因子详情读取失败')}}
async function loadLatestFactorVersion(factor){const factorId=factor.id??factor.factorId??route.params.id;const versions=await fetchFactorVersionsByFactor(factorId);const rows=normalize(versions);const preferred=rows.find(item=>item.id===factor.draftVersionId||item.versionId===factor.draftVersionId)||rows.find(item=>(item.status||item.publicationStatus)==='DRAFT')||rows.sort((a,b)=>Number(b.versionNo||0)-Number(a.versionNo||0))[0];const versionId=preferred?.id??preferred?.versionId;return versionId?fetchFactorVersion(versionId):null}
async function loadDomains(){loading.domains=true;try{domains.value=adaptDataDomainList(await fetchDataDomains()).filter(x=>x.code);dslForm.domainCode=domains.value[0]?.code||'';await loadTables()}catch(e){ElMessage.warning(e?.message||'数据域读取失败')}finally{loading.domains=false}}
async function handleDomainChange(){metadataRequestVersion.value++;dslForm.tableCode='';dslForm.fieldCode='';dslForm.groupBy=[];fields.value=[];filters.children.splice(0);await loadTables(false)}
async function handleTableChange(){metadataRequestVersion.value++;dslForm.fieldCode='';dslForm.groupBy=[];fields.value=[];filters.children.splice(0);await loadFields()}
async function loadTables(preserveTable=false){const d=domains.value.find(x=>x.code===dslForm.domainCode);if(!d?.id){tables.value=[];return}const requestedTable=preserveTable?dslForm.tableCode:'';tables.value=adaptSemanticTableList(await fetchSemanticTables(d.id)).filter(x=>x.code);dslForm.tableCode=requestedTable&&tables.value.some(x=>x.code===requestedTable)?requestedTable:'';if(dslForm.tableCode)await loadFields()}
async function loadFields(){const requestId=++metadataRequestVersion.value;const d=domains.value.find(x=>x.code===dslForm.domainCode);if(!d?.id||!dslForm.tableCode){fields.value=[];return}try{const data=await fetchSemanticTableFields(d.id,dslForm.tableCode);if(requestId!==metadataRequestVersion.value)return;fields.value=adaptSemanticFieldList(data).map(normalizeSemanticField).filter(x=>x.code);pruneFieldReferences()}catch(e){if(requestId===metadataRequestVersion.value)ElMessage.warning(e?.message||'语义字段读取失败')}}
function pruneFieldReferences(){const valid=new Set(fields.value.map(x=>x.code));if(!valid.has(dslForm.fieldCode))dslForm.fieldCode='';dslForm.groupBy=dslForm.groupBy.filter(code=>valid.has(code));pruneFilterNode(filters,valid)}
function pruneFilterNode(node,valid){if(!node)return;if(node.nodeType==='PREDICATE'&&!valid.has(node.fieldCode)){node.fieldCode='';node.value='';node.operator='EQ'};(node.children||[]).forEach(child=>pruneFilterNode(child,valid));if(node.child)pruneFilterNode(node.child,valid)}
async function loadParameterSchema(){if(!template.templateId)return;loading.template=true;try{const data=await fetchFactorTemplateParameterSchema(template.templateId);parameters.value=normalize(data?.parameters??data);parameters.value.forEach(x=>{if(!(x.code in parameterValues))parameterValues[x.code]=x.defaultValue??''})}catch(e){ElMessage.error(e?.message||'模板参数读取失败')}finally{loading.template=false}}
function selectAggregation(value){dslForm.aggregation=value;if(value==='COUNT')dslForm.fieldCode=''}
function buildDsl(){return buildFactorDsl({domainCode:dslForm.domainCode,semanticTableCode:dslForm.tableCode,aggregation:dslForm.aggregation,fieldCode:dslForm.fieldCode,groupBy:dslForm.groupBy,filters})}
function hasPeriodParameter(node){return !!node&&(node.nodeType==='PREDICATE'&&node.parameter==='period'||(node.children||[]).some(hasPeriodParameter)||hasPeriodParameter(node.child))}
async function saveFactor(){if(!(await basicFormRef.value?.validate().catch(()=>false)))return;if(!dslForm.domainCode||!dslForm.tableCode)return ElMessage.warning('请选择数据域和语义表');const valid=new Set(fields.value.map(x=>x.code));if((dslForm.fieldCode&&!valid.has(dslForm.fieldCode))||dslForm.groupBy.some(x=>!valid.has(x)))return ElMessage.warning('统计字段必须来自当前语义表');const errors=validateFilterNode(filters);if(errors.length)return ElMessage.warning(errors[0]);if(hasPeriodParameter(filters)&&!tables.value.find(x=>x.code===dslForm.tableCode)?.defaultTimeSemanticFieldCode)return ElMessage.warning('当前语义表未配置默认时间字段，无法执行统计周期试算');if(dslForm.aggregation!=='COUNT'&&!dslForm.fieldCode)return ElMessage.warning('请选择统计字段');loading.save=true;try{const payload={name:basicForm.name,description:basicForm.description,category:basicForm.category||null,dsl:buildDsl(),resourceVersion:resourceVersion.value};const result=isCreate.value?(template.versionId?await instantiateFactorTemplateVersion(template.versionId,{parameters:parameterValues,overrides:{code:basicForm.code,name:basicForm.name,description:basicForm.description}}):await createFactor({code:basicForm.code,name:basicForm.name,description:basicForm.description,category:basicForm.category||undefined,dsl:buildDsl()})):await updateFactor(route.params.id,payload);resourceVersion.value=Number(result?.resourceVersion??result?.version??resourceVersion.value);ElMessage.success(isCreate.value?`因子已保存${result?.draftVersionId?'，版本 ID：'+result.draftVersionId:''}`:'因子修改已保存')}catch(e){ElMessage.error(e?.message||'因子保存失败')}finally{loading.save=false}}
function fieldOptionLabel(field){return field.sensitive?`${field.label}（敏感）`:field.label}
function describeNode(node){if(!node)return'';if(node.nodeType==='PREDICATE'){const field=fieldByCode(fields.value,node.fieldCode);const label=field?.label||'未选择字段';if(node.parameter==='period')return `${label}在统计周期内`;const value=Array.isArray(node.value)?node.value.join('至'):node.value;return `${label}${operatorLabel(node.operator)}${value||'未填写'}`}if(node.nodeType==='NOT')return `不满足（${describeNode(node.child)}）`;return (node.children||[]).map(describeNode).filter(Boolean).join(node.nodeType==='OR'?'，或':'，且')}
function operatorLabel(value){return({EQ:'等于',IN:'属于',IN_VALUE_SET:'属于值集',GTE:'晚于或等于',LTE:'早于或等于',GT:'大于',LT:'小于',BETWEEN:'在统计周期内'})[value]||value||''}function normalize(x){if(Array.isArray(x))return x;return x?.records||x?.list||x?.items||x?.data||[]}
</script>
<style scoped lang="scss">.editor-section{margin-bottom:16px;padding:18px}.section-title{display:flex;gap:12px;align-items:flex-start;justify-content:flex-start;min-width:0;margin-bottom:16px}.section-title>div{min-width:0;flex:1}.section-title>span{display:flex;align-items:center;justify-content:center;width:28px;height:28px;color:#fff;background:#1890ff;border-radius:50%;font-weight:600}.section-title h2{margin:0 0 4px;font-size:16px}.section-title p{margin:0;color:#8c8c8c;font-size:13px}.business-summary{display:flex;gap:12px;align-items:center;margin-bottom:16px;padding:14px;background:#f7fbff;border:1px solid #d6ecff;border-radius:6px}.business-summary span,.business-summary small{color:#8c8c8c}.business-summary strong{color:#1677c2}.measure-cards{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.measure-card{padding:14px;text-align:left;background:#fff;border:1px solid #e5e8ef;border-radius:6px;cursor:pointer}.measure-card strong,.measure-card span{display:block}.measure-card span{margin-top:6px;color:#8c8c8c;font-size:12px}.measure-card.active{border-color:#1890ff;background:#f7fbff}.measure-card.active strong{color:#1677c2}.measure-field{margin-top:16px}.group-by-form{margin-top:18px;padding-top:16px;border-top:1px solid #edf0f5}.rule-explanation{display:flex;gap:12px;align-items:flex-start;margin-top:14px;padding:12px 14px;background:#fffbe6;border:1px solid #ffe58f;border-radius:6px}.rule-explanation strong{flex:0 0 auto;color:#ad6800}.rule-explanation span{color:#614700;line-height:20px}.section-footer{margin-top:10px;text-align:right}@media(max-width:900px){.measure-cards{grid-template-columns:repeat(2,1fr)}}:deep(.el-select),:deep(.el-input),:deep(.el-date-editor){width:100%}</style>


