<template>
  <div class="idmp-page"><PageHeader :title="isCreate ? '新建因子模板' : '编辑因子模板版本'" :status="version.publicationStatus || 'DRAFT'" :status-label="version.publicationStatus || '草稿'"><template #actions><div class="page-toolbar"><el-button @click="router.push('/factor/templates')">返回目录</el-button><el-button v-if="!isCreate && editable" :loading="saving" @click="save">保存草稿</el-button><el-button v-if="!isCreate && editable" :loading="validating" @click="validate">校验</el-button><el-button v-if="!isCreate && editable" type="primary" :loading="publishing" @click="publish">发布</el-button><el-button v-if="!isCreate && version.publicationStatus === 'PUBLISHED'" type="primary" @click="instantiate">使用模板创建因子</el-button></div></template></PageHeader>
    <section class="surface-card editor-card"><el-alert title="模板定义以 JSON 原样提交后端；保存、校验、发布均受 resourceVersion 并发控制。" type="info" :closable="false" /><el-form label-position="top"><div class="grid"><el-form-item label="模板编码"><el-input v-model.trim="form.code" :disabled="!isCreate" /></el-form-item><el-form-item label="模板名称"><el-input v-model.trim="form.name" :disabled="!editable && !isCreate" /></el-form-item><el-form-item label="因子类型范围"><el-input v-model.trim="form.factorTypeScope" placeholder="例如 ATOMIC" :disabled="!editable && !isCreate" /></el-form-item></div><el-form-item label="说明"><el-input v-model="form.description" type="textarea" /></el-form-item><el-form-item label="templateDefinition（必填）"><el-input v-model="form.templateDefinition" type="textarea" :rows="16" class="mono" /></el-form-item><el-form-item label="outputDescriptor"><el-input v-model="form.outputDescriptor" type="textarea" :rows="5" class="mono" /></el-form-item><el-form-item label="parameters"><el-input v-model="form.parameters" type="textarea" :rows="5" class="mono" /></el-form-item></el-form><el-alert v-if="diagnostics" :title="diagnostics" type="warning" :closable="false" /></section>
  </div>
</template>
<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { useRoute, useRouter } from 'vue-router'
import PageHeader from '@/idmp/components/PageHeader.vue'
import { createFactorTemplate, fetchFactorTemplateVersion, publishFactorTemplateVersion, updateFactorTemplateVersion, validateFactorTemplateVersion } from '@/idmp/api/modules/factors'
const route = useRoute(); const router = useRouter(); const isCreate = computed(() => route.name === 'FactorTemplateCreate'); const saving = ref(false); const validating = ref(false); const publishing = ref(false); const diagnostics = ref(''); const template = ref({}); const version = reactive({}); const form = reactive({ code: '', name: '', description: '', factorTypeScope: 'ATOMIC', templateDefinition: json(defaultDefinition()), outputDescriptor: json({ valueType: 'DECIMAL', unit: 'PERSON_TIME' }), parameters: '[]' }); const editable = computed(() => version.publicationStatus !== 'PUBLISHED')
async function load() { if (isCreate.value) return; try { const result = await fetchFactorTemplateVersion(route.params.versionId); template.value = result.template || {}; Object.assign(version, result.version || result); const source = result.version || result; Object.assign(form, { code: template.value.code || source.code || '', name: template.value.name || source.name || '', description: template.value.description || source.description || '', factorTypeScope: template.value.factorTypeScope || source.factorTypeScope || 'ATOMIC', templateDefinition: json(source.templateDefinition || defaultDefinition()), outputDescriptor: json(source.outputDescriptor || {}), parameters: json(source.parameters || []) }) } catch (error) { ElMessage.error(error?.message || '模板版本读取失败') } }
function payload(includeCode = false) { try { const data = { resourceVersion: version.resourceVersion, name: form.name, description: form.description, factorTypeScope: form.factorTypeScope, templateDefinition: JSON.parse(form.templateDefinition), outputDescriptor: JSON.parse(form.outputDescriptor || '{}'), parameters: JSON.parse(form.parameters || '[]') }; return includeCode ? { code: form.code, ...data } : data } catch { ElMessage.error('请检查 JSON 格式'); return null } }
async function save() { const data = payload(isCreate.value); if (!data || saving.value) return; saving.value = true; try { const result = isCreate.value ? await createFactorTemplate(data) : await updateFactorTemplateVersion(route.params.versionId, data); const created = result.version || result; if (isCreate.value) { ElMessage.success('模板已创建'); await router.replace(`/factor/templates/${encodeURIComponent((result.template || {}).id || (result.template || {}).templateId)}/versions/${encodeURIComponent(created.id || created.versionId)}`) } else { Object.assign(version, created); ElMessage.success('草稿已保存') } } catch (error) { ElMessage.error(error?.message || '保存失败') } finally { saving.value = false } }
async function validate() { if (validating.value) return; validating.value = true; try { const result = await validateFactorTemplateVersion(route.params.versionId); Object.assign(version, result.version || result); diagnostics.value = listDiagnostics(result.diagnostics); ElMessage.success(result.valid ? '模板校验通过' : '模板校验未通过') } catch (error) { ElMessage.error(error?.message || '校验失败') } finally { validating.value = false } }
async function publish() { try { await ElMessageBox.confirm('发布后该版本将不可编辑，确认继续？', '发布模板', { type: 'warning' }) } catch { return } publishing.value = true; try { const result = await publishFactorTemplateVersion(route.params.versionId, version.resourceVersion); Object.assign(version, result.version || result); ElMessage.success('模板版本已发布') } catch (error) { ElMessage.error(error?.message || '发布失败') } finally { publishing.value = false } }
function instantiate() { router.push({ path: '/factor/edit', query: { templateId: template.value.id || route.params.templateId, versionId: version.id || route.params.versionId } }) }
function defaultDefinition() { return { schemaVersion: '1.0', dslType: 'FACTOR', primaryDomain: { domainCode: '' }, filters: { nodeType: 'TRUE' }, aggregation: { function: 'COUNT' }, groupBy: [], parameters: [], output: { valueType: 'DECIMAL', semanticKind: 'MEASURE', unit: 'PERSON_TIME', nullable: false, precision: 30, scale: 10, grain: [] }, applicableDomains: [], allowedGrains: [], drillPathVersionIds: [] } }
function json(value) { return JSON.stringify(value, null, 2) }; function listDiagnostics(value) { return Array.isArray(value) ? value.map(item => item.message || JSON.stringify(item)).join('；') : '' }; onMounted(load)
</script>
<style scoped lang="scss">.editor-card { padding: 20px; }.grid { display:grid; grid-template-columns:repeat(3,minmax(0,1fr)); gap:16px; }.mono :deep(textarea) { font-family:Consolas, monospace; font-size:12px; line-height:1.5; } @media(max-width:900px){.grid{grid-template-columns:1fr}}</style>
