<template>
  <div class="idmp-page standardization-page">
    <PageHeader title="源值标准化">
      <template #meta><span class="data-source-badge is-live">真实接口</span><span class="header-meta">{{ sourceField || `映射 ${mappingId}` }}</span></template>
      <template #actions><el-button @click="router.push({ name: 'DataDomainManagement' })">返回数据模型</el-button><el-button :loading="loading" @click="loadAll">刷新</el-button></template>
    </PageHeader>

    <StatePanel v-if="error" type="error" title="标准化数据加载失败" :description="error" />
    <template v-else>
      <section class="profile-grid"><article v-for="item in profileCards" :key="item.label" class="surface-card profile-card"><span>{{ item.label }}</span><strong>{{ item.value }}</strong></article></section>

      <section class="surface-card table-card"><div class="section-title"><div><h2>源字段值画像</h2><p class="section-title__description">读取真实源字段离散值和出现频次，不修改源数据。</p></div></div><el-table v-if="profileItems.length" :data="profileItems"><el-table-column prop="value" label="源值" min-width="180"><template #default="{ row }">{{ row.nullValue ? 'NULL' : row.value }}</template></el-table-column><el-table-column prop="count" label="记录数" width="140" /><el-table-column prop="percentage" label="占比" width="140"><template #default="{ row }">{{ row.percentage == null ? '—' : `${Number(row.percentage).toFixed(2)}%` }}</template></el-table-column></el-table><StatePanel v-else type="empty" title="暂无源值画像" description="当前映射没有返回离散值。" /></section>

      <section class="surface-card table-card">
        <div class="section-title section-title--toolbar"><div><h2>转换规则</h2><p class="section-title__description">{{ rule?.name || '尚未配置转换规则' }} · resourceVersion {{ ruleVersion?.resourceVersion ?? '—' }}</p></div><div><el-button v-if="versionId" :loading="previewLoading" @click="loadPreview">执行预览</el-button><el-button v-if="versionId" type="primary" :loading="validating" @click="validate">校验</el-button><el-button v-if="versionId" type="success" :loading="publishing" :disabled="!canPublish" @click="publish">发布</el-button><el-button v-if="!versionId" type="primary" :loading="creating" @click="createRule">创建规则</el-button></div></div>
        <div v-if="ruleVersion" class="rule-meta"><span>规则版本 {{ ruleVersion.versionNo || ruleVersion.id }}</span><span>状态 {{ ruleVersion.publicationStatus || '—' }}</span><span>未匹配策略 {{ form.unmatchedPolicy }}</span><span>标准化器 {{ form.normalizers.join('、') || '—' }}</span></div>
        <el-form v-if="ruleVersion || creating" label-position="top" class="rule-form"><el-form-item label="规则名称"><el-input v-model.trim="form.name" :disabled="!canEditRule" /></el-form-item><el-form-item label="规则说明"><el-input v-model="form.description" type="textarea" :disabled="!canEditRule" /></el-form-item><el-form-item label="未匹配策略"><el-select v-model="form.unmatchedPolicy" :disabled="!canEditRule"><el-option label="拒绝" value="REJECT" /><el-option label="保留源值" value="KEEP_SOURCE" /><el-option label="置空" value="SET_NULL" /></el-select></el-form-item><el-form-item label="空值策略"><el-select v-model="form.nullPolicy" :disabled="!canEditRule"><el-option label="保留空值" value="KEEP_NULL" /><el-option label="拒绝" value="REJECT" /></el-select></el-form-item><el-form-item label="标准化器"><el-checkbox-group v-model="form.normalizers" :disabled="!canEditRule"><el-checkbox label="TRIM" /><el-checkbox label="UPPER" /><el-checkbox label="LOWER" /></el-checkbox-group></el-form-item></el-form>
        <div v-if="ruleVersion" class="mapping-heading"><h3>源值映射</h3><el-button size="small" :disabled="!canEditRule" @click="addMapping">新增映射</el-button></div>
        <el-table v-if="ruleVersion" :data="form.mappings"><el-table-column label="源值" min-width="180"><template #default="{ row }"><el-input v-model="row.sourceValue" :disabled="!canEditRule" /></template></el-table-column><el-table-column label="目标值项" min-width="220"><template #default="{ row }"><el-select v-model="row.targetItemCode" filterable :disabled="!canEditRule || !valueSetItems.length" placeholder="选择标准值"><el-option v-for="item in valueSetItems" :key="item.code" :label="`${item.label}（${item.code}）`" :value="item.code" /></el-select></template></el-table-column><el-table-column label="目标标签" min-width="160"><template #default="{ row }">{{ row.targetLabel || valueSetLabel(row.targetItemCode) || '—' }}</template></el-table-column><el-table-column label="操作" width="90"><template #default="{ $index }"><el-button link type="danger" :disabled="!canEditRule" @click="form.mappings.splice($index, 1)">删除</el-button></template></el-table-column></el-table>
        <div v-if="ruleVersion && canEditRule" class="rule-save"><el-button type="primary" :loading="saving" @click="saveRule">保存规则</el-button><span>保存携带当前 resourceVersion；发生冲突时请刷新后重试。</span></div>
      </section>

      <section class="surface-card table-card"><div class="section-title"><div><h2>转换预览结果</h2><p class="section-title__description">仅预览标准化结果，不写回源数据。</p></div></div><div v-if="previewResult" class="profile-grid preview-stats"><article class="profile-card"><span>检查不同值</span><strong>{{ previewResult.inspectedDistinctCount }}</strong></article><article class="profile-card"><span>匹配值</span><strong>{{ previewResult.matchedCount }}</strong></article><article class="profile-card"><span>未匹配值</span><strong>{{ previewResult.unmatchedCount }}</strong></article></div><el-table v-if="previewItems.length" :data="previewItems"><el-table-column prop="sourceValue" label="源值" /><el-table-column prop="normalizedSourceValue" label="标准化后" /><el-table-column prop="targetItemCode" label="目标值项" /><el-table-column prop="targetLabel" label="目标标签" /><el-table-column prop="status" label="结果" /></el-table><StatePanel v-else type="empty" title="暂无预览结果" description="保存或加载规则后执行预览。" /></section>
    </template>
  </div>
</template>

<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { useRoute, useRouter } from 'vue-router'
import PageHeader from '@/idmp/components/PageHeader.vue'
import StatePanel from '@/idmp/components/StatePanel.vue'
import { createTransformRule, fetchSourceTransformRule, fetchSourceValueProfile, previewTransformRule, publishTransformRule, updateTransformRuleVersion, validateTransformRule } from '@/idmp/api/modules/transformRules'
import { fetchSemanticFieldValueSet, fetchValueSetItems } from '@/idmp/api/modules/valueSets'

const route = useRoute(); const router = useRouter(); const mappingId = String(route.params.mappingId || '')
const sourceField = computed(() => String(route.query.sourceField || '')); const profile = ref(null); const profileItems = ref([]); const rule = ref(null); const ruleVersion = ref(null); const valueSetItems = ref([]); const previewResult = ref(null); const previewItems = ref([]); const loading = ref(false); const creating = ref(false); const saving = ref(false); const validating = ref(false); const publishing = ref(false); const error = ref('')
const form = reactive({ name: '', description: '', unmatchedPolicy: 'REJECT', nullPolicy: 'KEEP_NULL', normalizers: ['TRIM'], mappings: [] })
const versionId = computed(() => ruleVersion.value?.id || '')
const canEditRule = computed(() => ['DRAFT', 'VALIDATED'].includes(String(ruleVersion.value?.publicationStatus || '').toUpperCase()))
const canPublish = computed(() => Boolean(versionId.value) && String(ruleVersion.value?.publicationStatus).toUpperCase() === 'VALIDATED')
const profileCards = computed(() => [{ label: '总记录数', value: profile.value?.totalCount ?? '—' }, { label: '空值数', value: profile.value?.nullCount ?? '—' }, { label: '不同值', value: profile.value?.distinctCount ?? '—' }, { label: '规则状态', value: rule.value?.status || '未配置' }])
function fillForm(version) { Object.assign(form, { name: rule.value?.name || '', description: rule.value?.description || '', unmatchedPolicy: version?.unmatchedPolicy || 'REJECT', nullPolicy: version?.nullPolicy || 'KEEP_NULL', normalizers: [...(version?.normalizers || ['TRIM'])], mappings: (version?.mappings || []).map(item => ({ ...item })) }) }
async function loadAll() { loading.value = true; error.value = ''; try { const [profileData, ruleData] = await Promise.all([fetchSourceValueProfile(mappingId, { page: 1, size: 100 }), fetchSourceTransformRule(mappingId)]); profile.value = profileData; profileItems.value = profileData?.items || profileData?.topValues || []; rule.value = ruleData?.rule || null; ruleVersion.value = ruleData?.version || null; await loadValueSetItems(ruleVersion.value); fillForm(ruleVersion.value) } catch (err) { error.value = err?.message || '标准化数据加载失败。' } finally { loading.value = false } }
async function loadValueSetItems(version) { valueSetItems.value = []; const fieldId = version?.semanticFieldId || route.query.fieldId; if (!fieldId) return; const binding = await fetchSemanticFieldValueSet(fieldId); const versionId = binding?.publishedVersion?.id || version?.valueSetVersionId; if (versionId) { const data = await fetchValueSetItems(versionId); valueSetItems.value = Array.isArray(data) ? data : (data?.items || []) } }
function valueSetLabel(code) { return valueSetItems.value.find(item => item.code === code)?.label || '' }
function addMapping() { form.mappings.push({ sourceValue: '', targetItemCode: '' }) }
async function createRule() { if (creating.value) return; if (!valueSetItems.value.length) await loadValueSetItems(null); const first = profileItems.value.find(item => !item.nullValue && item.value !== null && item.value !== undefined); const target = valueSetItems.value[0]?.code; if (!first || !target) { ElMessage.warning('请先确保源值画像和已发布值集均可用'); return } creating.value = true; try { const data = await createTransformRule(mappingId, { name: sourceField.value ? `${sourceField.value}源值标准化` : '源值标准化', description: '', unmatchedPolicy: form.unmatchedPolicy, nullPolicy: form.nullPolicy, normalizers: form.normalizers, mappings: [{ sourceValue: String(first.value), targetItemCode: target }] }); rule.value = data?.rule || null; ruleVersion.value = data?.version || null; await loadValueSetItems(ruleVersion.value); fillForm(ruleVersion.value); ElMessage.success('转换规则草稿创建成功，请继续补充其他源值映射') } catch (err) { ElMessage.error(err?.message || '转换规则创建失败') } finally { creating.value = false } }
async function saveRule() { if (!versionId.value || saving.value) return; if (!form.name || !form.mappings.length) { ElMessage.warning('规则名称和至少一条映射不能为空'); return } saving.value = true; try { const data = await updateTransformRuleVersion(versionId.value, { resourceVersion: ruleVersion.value.resourceVersion, ...form }); rule.value = data?.rule || rule.value; ruleVersion.value = data?.version || ruleVersion.value; fillForm(ruleVersion.value); previewResult.value = null; previewItems.value = []; ElMessage.success('转换规则保存成功') } catch (err) { ElMessage.error(err?.message || '规则保存失败；如提示版本冲突，请刷新后重试。') } finally { saving.value = false } }
async function loadPreview() { if (!versionId.value) return; try { const data = await previewTransformRule(versionId.value, 100); previewResult.value = data; previewItems.value = data?.items || [] } catch (err) { ElMessage.error(err?.message || '转换规则预览失败') } }
async function validate() { validating.value = true; try { const data = await validateTransformRule(versionId.value); previewResult.value = data; if (ruleVersion.value && data.resourceVersion != null) ruleVersion.value.resourceVersion = data.resourceVersion; ruleVersion.value.publicationStatus = data.valid ? 'VALIDATED' : 'DRAFT'; ElMessage[data.valid ? 'success' : 'warning'](data.valid ? '转换规则校验通过' : '转换规则校验未通过') } catch (err) { ElMessage.error(err?.message || '转换规则校验失败') } finally { validating.value = false } }
async function publish() { try { await ElMessageBox.confirm('发布后规则将绑定到源字段映射，确认继续？', '确认发布', { type: 'warning' }) } catch { return } publishing.value = true; try { const data = await publishTransformRule(versionId.value, ruleVersion.value.resourceVersion); rule.value = data?.rule || rule.value; ruleVersion.value = data?.version || ruleVersion.value; ElMessage.success('转换规则发布成功') } catch (err) { ElMessage.error(err?.message || '转换规则发布失败；请确认已校验且资源版本最新。') } finally { publishing.value = false } }
onMounted(loadAll)
</script>

<style scoped>
.profile-grid { display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 16px; margin-bottom: 16px; }.profile-card { padding: 18px; }.profile-card span { color: var(--idmp-text-secondary); font-size: 12px; }.profile-card strong { display: block; margin-top: 8px; font-size: 24px; }.table-card { margin-bottom: 16px; }.section-title--toolbar,.mapping-heading,.rule-save { display: flex; justify-content: space-between; align-items: center; gap: 16px; }.rule-form { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 0 16px; margin-top: 16px; }.rule-form .el-form-item:nth-child(2) { grid-column: span 2; }.rule-meta { display: flex; flex-wrap: wrap; gap: 24px; padding: 12px 0; color: var(--idmp-text-secondary); font-size: 12px; }.mapping-heading { margin: 8px 0 12px; }.mapping-heading h3 { margin: 0; }.rule-save { justify-content: flex-start; margin-top: 16px; color: var(--idmp-text-secondary); font-size: 12px; }.preview-stats { margin: 16px 0 0; }
</style>
