<template>
  <div class="idmp-page sql-import-page">
    <PageHeader title="SQL 导入因子/指标"><template #actions><el-button v-if="canStartNewImport" type="primary" plain @click="startNewImport">开始新的导入</el-button><el-button :icon="ArrowLeft" @click="router.push('/indicator')">返回指标目录</el-button></template></PageHeader>
    <section class="surface-card section"><div class="section-heading"><div><h2>1. 提交并解析 SQL</h2><span>创建导入会话后，系统只解析，不创建资源。</span></div><el-button type="primary" :loading="createLoading" :disabled="Boolean(importTask?.importId) || !sql.trim()" @click="createImport">解析 SQL</el-button></div><el-input v-model="sql" type="textarea" :rows="13" class="sql-editor" placeholder="请输入 MySQL 8 SELECT SQL" /></section>

    <section v-if="importTask" class="surface-card section">
      <div class="section-heading"><div><h2>导入会话</h2><span>{{ importTask.step || '等待操作' }}</span></div><el-tag :type="tagType">{{ importTask.status }}</el-tag></div>
      <el-alert v-if="importTask.error" type="error" :closable="false" show-icon :title="importTask.error" />
      <div v-if="operationError" class="operation-error">
        <el-alert :type="operationError.conflict ? 'warning' : 'error'" :closable="false" show-icon :title="operationError.conflict ? '资源编码或名称冲突' : '导入操作失败'" :description="operationError.message" />
        <dl><div><dt>导入会话</dt><dd>{{ importTask.importId || '—' }}</dd></div><div><dt>业务码</dt><dd>{{ operationError.code || '—' }}</dd></div><div><dt>traceId</dt><dd>{{ operationError.traceId || '—' }}</dd></div><div v-if="operationError.resource"><dt>冲突资源</dt><dd>{{ operationError.resource.type || 'RESOURCE' }} · {{ operationError.resource.code || operationError.resource.id }} · {{ operationError.resource.status || '状态未知' }}</dd></div></dl>
        <div class="error-actions"><el-button v-if="operationError.conflict && canEditMetadata" type="primary" @click="useNextCodeBatch">使用下一批编码并继续</el-button><el-button v-if="operationError.resource?.id" @click="openConflictResource">打开冲突资源</el-button></div>
      </div>
      <div v-if="preview" class="preview-summary"><span>解析到 {{ preview.factors.length }} 个因子</span><span v-if="preview.normalizedSql">已生成规范化 SQL</span></div>
      <div v-if="preview?.tables.length" class="block"><h3>表映射</h3><el-table :data="preview.tables" border><el-table-column prop="physicalTable" label="物理表" min-width="180" /><el-table-column label="映射" min-width="340"><template #default="{ row }"><el-select v-model="tableMappings[row.physicalTable]" :disabled="!canEditMetadata || !row.candidates.length" filterable :placeholder="mappingPlaceholder(row)"><el-option v-for="item in row.candidates" :key="item.viewMappingId" :value="item.viewMappingId" :label="`${item.domainCode} / ${item.semanticTableCode}`" /><el-option v-if="!row.candidates.length && tableMappings[row.physicalTable]" :value="tableMappings[row.physicalTable]" label="已由 SQL 解析自动确定" /></el-select><small v-if="!row.candidates.length" class="mapping-hint">{{ tableMappings[row.physicalTable] ? '当前映射已由 SQL 解析自动确定，无需选择。' : '后端未返回可选映射；请先完成该物理表的数据治理映射。' }}</small></template></el-table-column></el-table></div>
      <div v-if="preview?.diagnostics.length" class="block"><h3>解析诊断</h3><el-alert v-for="item in preview.diagnostics" :key="`${item.code}-${item.path}`" :type="item.severity === 'ERROR' ? 'error' : 'warning'" :closable="false" :title="`${item.code} · ${item.message}`" :description="item.suggestion" /></div>
    </section>

    <template v-if="canEditMetadata">
      <section class="surface-card section"><div class="section-heading"><div><h2>2. 确认治理元数据</h2><span>确认后才能试算。</span></div></div><el-form label-position="top"><el-radio-group v-model="scope"><el-radio label="FACTORS_ONLY">仅创建因子</el-radio><el-radio label="FACTORS_AND_INDICATOR">创建因子及指标</el-radio></el-radio-group><el-form-item label="业务分类"><el-input v-model.trim="category" maxlength="64" /></el-form-item></el-form>
        <div class="factor-list"><div v-for="factor in factorMetadata" :key="factor.key" class="factor"><strong>{{ factor.key }}</strong><small>CTE 输出：{{ factorOutputAlias(factor.key) || '-' }}</small><div class="factor-fields"><el-input v-model="factor.code" placeholder="因子编码（已按解析建议预填）" @input="factor.code = normalizeCode(factor.code)" /><el-input v-model.trim="factor.name" placeholder="因子名称（已按解析建议预填）" /><el-input v-model.trim="factor.description" placeholder="因子说明" /><el-select v-model="factor.missingRowPolicy" placeholder="缺行策略"><el-option label="保留空值" value="KEEP_NULL" /><el-option label="按零处理" value="ZERO" /></el-select><el-select v-model="factor.calculationMode" @change="onFactorModeChange(factor)"><el-option label="静态（全量一次计算）" value="STATIC" /><el-option label="时序（按周期计算）" value="TEMPORAL" /></el-select><el-select v-if="factor.calculationMode === 'TEMPORAL' && timeFieldOptions(factor).length" v-model="factor.timeField" filterable placeholder="确认时间字段"><el-option v-for="field in timeFieldOptions(factor)" :key="field" :label="field" :value="field" /></el-select><el-input v-else-if="factor.calculationMode === 'TEMPORAL'" v-model.trim="factor.timeField" placeholder="填写 SQL 中已使用的物理时间字段，例如 t.ADMISSION_TIME" /><small v-if="factor.calculationMode === 'TEMPORAL' && !timeFieldOptions(factor).length" class="time-field-hint">解析结果未返回候选字段；请从上方 SQL 中复制已使用的日期/时间物理字段或“别名.字段名”。后端会在提交时校验。</small></div></div></div>
      </section>
      <section v-if="scope === 'FACTORS_AND_INDICATOR'" class="surface-card section"><h2>指标信息</h2><el-form label-position="top"><div class="grid"><el-form-item label="指标编码"><el-input v-model="indicator.code" @input="indicator.code = normalizeCode(indicator.code)" /></el-form-item><el-form-item label="指标名称"><el-input v-model.trim="indicator.name" /></el-form-item></div><el-form-item label="指标说明"><el-input v-model.trim="indicator.description" type="textarea" /></el-form-item><el-form-item v-if="allTemporal" label="时间下钻"><el-switch v-model="indicator.timeDrillEnabled" active-text="启用" inactive-text="关闭" /></el-form-item><el-alert v-else-if="mixedModes" type="warning" :closable="false" title="当前因子同时包含静态与时序模式，不能创建同一个指标；请改为仅创建因子，或统一全部因子的计算模式。" /><el-alert v-else type="info" :closable="false" title="静态指标不支持时间下钻。" /></el-form></section>
      <section class="surface-card section"><h2>解析结果预览</h2><el-tabs><el-tab-pane v-for="factor in preview.factors" :key="factor.key" :label="factor.key"><pre>{{ JSON.stringify(factor.dsl, null, 2) }}</pre></el-tab-pane><el-tab-pane label="指标公式"><pre>{{ JSON.stringify(preview.formula?.template || {}, null, 2) }}</pre></el-tab-pane></el-tabs></section>
      <div class="action-bar"><el-button type="primary" :loading="metadataLoading" @click="submitMetadata">确认元数据并进入试算</el-button></div>
    </template>

    <section v-if="canTrial" class="surface-card section"><div class="section-heading"><div><h2>3. 导入试算</h2><span>{{ hasTemporalFactors ? (mixedModes ? '本次仅创建因子；时序因子使用所选周期，静态因子执行全量试算。' : '请选择完整的试算时间范围。') : '静态导入不传统计周期。' }}</span></div><el-button type="primary" :loading="trialLoading" @click="runTrial">发起试算</el-button></div><el-date-picker v-if="hasTemporalFactors" v-model="trialPeriod" type="datetimerange" value-format="YYYY-MM-DDTHH:mm:ss" start-placeholder="开始时间" end-placeholder="结束时间" /></section>
    <section v-if="canFinalize" class="surface-card section"><h2>4. 试算成功</h2><el-alert type="success" :closable="false" title="试算成功，尚未创建和发布正式资源。请核对资源级诊断后确认发布。" /><ResourceTable :resources="importTask.resources" /><div class="action-bar"><el-button type="success" :loading="finalizeLoading" @click="finalizeImport">确认创建并发布</el-button></div></section>
    <section v-if="importTask?.resources.length && !canFinalize" class="surface-card section"><h2>资源状态</h2><ResourceTable :resources="importTask.resources" /></section>
    <section v-if="importTask?.status === 'FAILED' || importTask?.status === 'CLEANUP_FAILED'" class="surface-card section"><el-alert v-if="importTask.status === 'FAILED'" type="warning" :closable="false" title="重试会沿用原 SQL、原编码和原检查点；如果失败原因是 SQL、时间字段或编码错误，请放弃并清理，不要重试。" /><el-alert v-else type="error" :closable="false" title="半成品清理失败。请保留 importId、资源状态和 traceId 交由后端处理；不要复用本次编码。" /><div class="action-bar"><el-button type="primary" :loading="actionLoading" :disabled="importTask.status !== 'FAILED'" @click="retryImport">重试原任务</el-button><el-button type="danger" plain :loading="actionLoading" @click="abandonImport">放弃并清理</el-button></div></section>
    <section v-if="importTask?.status === 'ABANDONING'" class="surface-card section"><el-alert type="warning" :closable="false" show-icon title="正在清理未发布半成品，请等待状态变为 ABANDONED 后再开始新导入。" /></section>
    <section v-if="importTask?.status === 'ABANDONED'" class="surface-card section"><el-result icon="warning" title="导入已放弃，半成品清理已完成" sub-title="现在可以开始新的导入；如果相同编码仍冲突，请记录 importId 和 traceId，这是后端清理一致性问题。"><template #extra><el-button type="primary" @click="startNewImport">开始新的导入</el-button><el-button @click="router.push('/indicator')">返回指标目录</el-button></template></el-result></section>
    <section v-if="importTask?.status === 'SUCCEEDED'" class="surface-card section"><el-result icon="success" title="SQL 导入及发布已完成" sub-title="因子和指标已经由导入流程完成编译与发布。"><template #extra><el-button @click="router.push('/indicator')">返回指标目录</el-button><el-button v-if="importTask.result?.indicatorId" type="primary" @click="router.push(`/indicator/edit/${importTask.result.indicatorId}`)">查看指标</el-button><el-button v-if="importTask.result?.initializationBatchId" @click="router.push({ path: '/calc', query: { batchId: importTask.result.initializationBatchId } })">跟踪静态初始化批次</el-button></template></el-result><el-alert v-if="importTask.result?.initializationBatchId" :type="initializationStatus === 'SUCCEEDED' ? 'success' : initializationStatus === 'FAILED' ? 'error' : 'info'" :closable="false" show-icon :title="`初始化批次 ${importTask.result.initializationBatchId}：${initializationStatus || '正在查询'}`" /></section>
  </div>
</template>

<script setup>
import { computed, onBeforeUnmount, onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { ArrowLeft } from '@element-plus/icons-vue'
import { useRoute, useRouter } from 'vue-router'
import PageHeader from '@/idmp/components/PageHeader.vue'
import { buildSqlImportCreatePayload, buildSqlImportMetadataPayload, buildSqlImportTrialPayload, canFinalizeSqlImport, canSubmitSqlImportMetadata, canTrialSqlImport, mergeSqlFactorMetadata, nextSqlImportCode, normalizeSqlImportOperationError, normalizeSqlImportTask, shouldPollSqlImport } from '@/idmp/api/adapters/sqlImport'
import { abandonSqlImport, createSqlImport, fetchSqlImport, finalizeSqlImport, retrySqlImport, trialSqlImport, updateSqlImportMetadata } from '@/idmp/api/modules/sqlImports'
import { fetchCalcBatch } from '@/idmp/api/modules/calculation'

const ResourceTable = { props: { resources: { type: Array, default: () => [] } }, template: '<el-table :data="resources" size="small"><el-table-column prop="key" label="资源"/><el-table-column prop="type" label="类型"/><el-table-column label="状态"><template #default="{row}">{{ row.published ? "已发布" : row.compiled ? "已编译" : row.trial?.status || "处理中" }}</template></el-table-column><el-table-column label="诊断"><template #default="{row}">{{ row.diagnostics?.map(x => x.message || x).join("；") || "—" }}</template></el-table-column></el-table>' }
const router = useRouter(); const route = useRoute(); const sql = ref(''); const importTask = ref(null); const factorMetadata = ref([]); const tableMappings = reactive({}); const scope = ref('FACTORS_AND_INDICATOR'); const category = ref(''); const trialPeriod = ref([])
const indicator = reactive({ code: '', name: '', description: '', timeDrillEnabled: true, formula: null })
const operationError = ref(null); const createLoading = ref(false); const metadataLoading = ref(false); const trialLoading = ref(false); const finalizeLoading = ref(false); const actionLoading = ref(false); const initializationStatus = ref(''); let timer = null; let initializationTimer = null
const preview = computed(() => importTask.value?.preview || null); const canEditMetadata = computed(() => canSubmitSqlImportMetadata(importTask.value)); const canTrial = computed(() => canTrialSqlImport(importTask.value)); const canFinalize = computed(() => canFinalizeSqlImport(importTask.value)); const canStartNewImport = computed(() => ['ABANDONED', 'SUCCEEDED'].includes(String(importTask.value?.status || '').toUpperCase())); const hasTemporalFactors = computed(() => factorMetadata.value.some(x => x.calculationMode === 'TEMPORAL')); const allTemporal = computed(() => factorMetadata.value.length > 0 && factorMetadata.value.every(x => x.calculationMode === 'TEMPORAL')); const mixedModes = computed(() => hasTemporalFactors.value && factorMetadata.value.some(x => x.calculationMode === 'STATIC')); const tagType = computed(() => ({ SUCCEEDED: 'success', FAILED: 'danger', TRIAL_SUCCEEDED: 'success', READY_FOR_TRIAL: 'warning', AWAITING_METADATA: 'info', ABANDONED: 'info', CLEANUP_FAILED: 'danger' })[importTask.value?.status] || 'warning')
function key(prefix) { return `${prefix}-${Date.now()}-${Math.random().toString(16).slice(2)}` }; function normalizeCode(value) { return String(value || '').toUpperCase().replace(/[^A-Z0-9_]/g, '') }; function factorOutputAlias(id) { return preview.value?.factors.find(x => x.key === id)?.outputAlias }; function timeFieldOptions(factor) { return preview.value?.factors.find(x => x.key === factor.key)?.timeFields || [] }; function mappingPlaceholder(row) { return row.candidates.length ? '请选择语义映射' : (tableMappings[row.physicalTable] ? '已自动确定' : '后端未返回候选映射') }
function onFactorModeChange(factor) { if (factor.calculationMode === 'STATIC') factor.timeField = '' }
function accept(payload) { const task = normalizeSqlImportTask(payload); importTask.value = task; if (task.importId) router.replace({ query: { ...route.query, importId: task.importId } }); if (task.preview?.factors?.length && !factorMetadata.value.length) { factorMetadata.value = mergeSqlFactorMetadata([], task.preview.factors); task.preview.tables.forEach(x => { if (x.selectedViewMappingId) tableMappings[x.physicalTable] = x.selectedViewMappingId }) }; schedule(); if (task.status === 'SUCCEEDED' && task.result?.initializationBatchId) scheduleInitializationPoll(task.result.initializationBatchId) }
function schedule() { clearTimeout(timer); if (shouldPollSqlImport(importTask.value)) timer = setTimeout(refresh, 1500) }
async function refresh() { if (!importTask.value?.importId) return; try { accept(await fetchSqlImport(importTask.value.importId)) } catch (e) { ElMessage.error(e.message || '导入状态读取失败') } }
async function createImport() { operationError.value = null; createLoading.value = true; try { accept(await createSqlImport(buildSqlImportCreatePayload({ sql: sql.value, tableMappings }), key('sql-import'))); ElMessage.success('SQL 已解析，请确认治理元数据') } catch (e) { captureOperationError(e, 'SQL 解析失败') } finally { createLoading.value = false } }
function validateMetadata() { if (!factorMetadata.value.every(x => x.code && x.name && (x.calculationMode !== 'TEMPORAL' || x.timeField))) return '请补全因子编码、名称和时序因子的时间字段'; if (scope.value === 'FACTORS_AND_INDICATOR') { if (!indicator.code || !indicator.name) return '请填写指标编码和名称'; const modes = new Set(factorMetadata.value.map(x => x.calculationMode)); if (modes.size !== 1) return '创建指标时，全部因子必须使用相同计算模式'; if (!hasFormula(preview.value?.formula?.template)) return '解析结果没有可提交的指标公式，请调整 SQL 后重新解析，或改为仅创建因子' } return '' }
async function submitMetadata() { const message = validateMetadata(); if (message) return ElMessage.warning(message); operationError.value = null; metadataLoading.value = true; try { indicator.formula = preview.value?.formula?.template || {}; if (!allTemporal.value) indicator.timeDrillEnabled = false; let activeImportId = importTask.value.importId; if (needsMappedReparse()) { const previousImportId = activeImportId; const previousFactors = factorMetadata.value; const mappedTask = await createSqlImport(buildSqlImportCreatePayload({ sql: sql.value || preview.value?.normalizedSql, tableMappings }), key('sql-import-mapped')); accept(mappedTask); activeImportId = importTask.value.importId; if (!activeImportId) throw new Error('映射重解析未返回新的导入会话 ID'); factorMetadata.value = mergeSqlFactorMetadata(previousFactors, preview.value?.factors || []); indicator.formula = preview.value?.formula?.template || {}; const mappedValidation = validateMetadata(); if (mappedValidation) throw new Error(`映射重解析后需要重新确认：${mappedValidation}`); void abandonSqlImport(previousImportId, '已按人工确认的表映射重新创建导入会话', key('sql-reparse-cleanup')).catch(() => {}); } accept(await updateSqlImportMetadata(activeImportId, buildSqlImportMetadataPayload({ scope: scope.value, category: category.value, indicator, factors: factorMetadata.value }))); ElMessage.success('元数据已确认，可发起试算') } catch (e) { captureOperationError(e, '元数据提交失败') } finally { metadataLoading.value = false } }
async function runTrial() { const payload = buildSqlImportTrialPayload(factorMetadata.value, trialPeriod.value); if (hasTemporalFactors.value && (!payload.periodStart || !payload.periodEnd)) return ElMessage.warning('请选择完整试算周期'); operationError.value = null; trialLoading.value = true; try { accept(await trialSqlImport(importTask.value.importId, payload, key('sql-trial'))) } catch (e) { captureOperationError(e, '导入试算失败') } finally { trialLoading.value = false } }
async function finalizeImport() { operationError.value = null; finalizeLoading.value = true; try { accept(await finalizeSqlImport(importTask.value.importId, key('sql-finalize'))) } catch (e) { captureOperationError(e, '确认发布失败') } finally { finalizeLoading.value = false } }
async function retryImport() { operationError.value = null; actionLoading.value = true; try { accept(await retrySqlImport(importTask.value.importId, key('sql-retry'))) } catch (e) { captureOperationError(e, '重试失败') } finally { actionLoading.value = false } }
async function abandonImport() { try { await ElMessageBox.confirm('将异步清理尚未发布的半成品资源。清理完成前不能复用本次编码。', '确认放弃', { type: 'warning' }) } catch { return }; operationError.value = null; actionLoading.value = true; try { accept(await abandonSqlImport(importTask.value.importId, '用户放弃此次 SQL 导入', key('sql-abandon'))) } catch (e) { captureOperationError(e, '放弃失败') } finally { actionLoading.value = false } }
function captureOperationError(error, fallback) { const normalized = normalizeSqlImportOperationError(error); operationError.value = normalized; ElMessage.error(normalized.message || fallback) }
function useNextCodeBatch() { factorMetadata.value.forEach(item => { item.code = nextSqlImportCode(item.code); item.name = nextBatchName(item.name, item.code) }); if (scope.value === 'FACTORS_AND_INDICATOR') { indicator.code = nextSqlImportCode(indicator.code); indicator.name = nextBatchName(indicator.name, indicator.code) } operationError.value = null; ElMessage.success('已切换到下一批编码，请核对后重新确认元数据') }
function nextBatchName(name, code) { const suffix = code.match(/_R\d+$/)?.[0] || '_R02'; return `${String(name || '').replace(/_R\d+$/i, '')}${suffix}` }
function openConflictResource() { const resource = operationError.value?.resource; if (!resource?.id) return; const path = String(resource.type).toUpperCase().includes('INDICATOR') ? `/indicator/edit/${encodeURIComponent(resource.id)}` : `/factor/edit/${encodeURIComponent(resource.id)}`; router.push(path) }
function startNewImport() { clearTimeout(timer); clearTimeout(initializationTimer); importTask.value = null; factorMetadata.value = []; Object.keys(tableMappings).forEach(item => delete tableMappings[item]); scope.value = 'FACTORS_AND_INDICATOR'; category.value = ''; trialPeriod.value = []; initializationStatus.value = ''; operationError.value = null; Object.assign(indicator, { code: '', name: '', description: '', timeDrillEnabled: true, formula: null }); sql.value = ''; const query = { ...route.query }; delete query.importId; router.replace({ path: '/indicator/import/sql', query }) }
function hasFormula(formula) { return Boolean(formula && typeof formula === 'object' && (formula.root || formula.nodeType)) }
function needsMappedReparse() { return (preview.value?.tables || []).some(row => { const selected = String(tableMappings[row.physicalTable] || ''); return selected && selected !== String(row.selectedViewMappingId || '') }) }
function scheduleInitializationPoll(batchId) { clearTimeout(initializationTimer); initializationTimer = setTimeout(() => pollInitializationBatch(batchId), 500) }
async function pollInitializationBatch(batchId) { try { const batch = await fetchCalcBatch(batchId); initializationStatus.value = String(batch?.status || batch?.batchStatus || 'RUNNING').toUpperCase(); if (!['SUCCEEDED', 'SUCCESS', 'FAILED', 'CANCELLED', 'CANCELED', 'PARTIAL_SUCCEEDED'].includes(initializationStatus.value)) initializationTimer = setTimeout(() => pollInitializationBatch(batchId), 2000) } catch { initializationStatus.value = '暂未查询到批次状态'; initializationTimer = setTimeout(() => pollInitializationBatch(batchId), 3000) } }
onMounted(() => { if (route.query.importId) { importTask.value = { importId: String(route.query.importId), status: 'RUNNING', preview: { factors: [] }, resources: [] }; refresh() } }); onBeforeUnmount(() => { clearTimeout(timer); clearTimeout(initializationTimer) })
</script>

<style scoped lang="scss">.sql-import-page{padding-bottom:48px}.section{margin-bottom:16px;padding:18px}.section-heading{display:flex;justify-content:space-between;gap:16px;align-items:center}.section-heading h2,.section h2,.block h3{margin:0}.section-heading span{color:var(--idmp-text-helper);font-size:12px}.block{margin-top:18px}.block+.block{margin-top:12px}.block :deep(.el-alert)+:deep(.el-alert){margin-top:8px}.mapping-hint,.time-field-hint{display:block;margin-top:6px;color:var(--idmp-text-helper)}.operation-error{margin-top:14px}.operation-error dl{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px 16px;margin:12px 0}.operation-error dl div{min-width:0;padding:9px 10px;background:var(--idmp-field);border-radius:6px}.operation-error dt{color:var(--idmp-text-helper);font-size:12px}.operation-error dd{overflow-wrap:anywhere;margin:4px 0 0;font-family:Consolas,monospace}.error-actions{display:flex;flex-wrap:wrap;gap:10px}.sql-editor{margin-top:16px}.sql-editor :deep(textarea){font-family:Consolas,monospace;background:#111b24;color:#e6edf3}.preview-summary{display:flex;gap:20px;margin-top:12px;color:var(--idmp-text-helper)}.factor-list{display:grid;gap:12px;margin-top:18px}.factor{display:grid;gap:6px;padding:14px;border:1px solid var(--idmp-border-subtle)}.factor small{color:var(--idmp-text-helper)}.factor-fields,.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.action-bar{display:flex;justify-content:flex-end;margin:16px 0}.section pre{max-height:340px;overflow:auto;padding:12px;background:var(--idmp-field)}@media(max-width:800px){.factor-fields,.grid,.operation-error dl{grid-template-columns:1fr}.section-heading{align-items:stretch;flex-direction:column}}</style>
