<template>
  <div class="rule-group" :class="{ nested: depth > 0 }">
    <div class="rule-group__head"><span>{{ depth ? '嵌套条件组' : '满足以下条件' }}</span><el-radio-group v-model="node.nodeType" size="small" @change="emitUpdate"><el-radio-button label="AND">全部满足</el-radio-button><el-radio-button label="OR">任意满足</el-radio-button></el-radio-group><el-button v-if="depth" link type="danger" @click="$emit('remove')">删除条件组</el-button></div>
    <div v-if="!node.children?.length" class="rule-empty"><strong>尚未添加筛选条件</strong><span>例如：出院诊断属于某个值集、住院天数大于 0、手术级别等于四级。</span><el-button type="primary" plain size="small" @click="addPredicate">添加第一个条件</el-button></div>
    <div v-for="(child,index) in node.children" :key="child.id" class="rule-row" draggable="true" @dragstart="dragStart(index)" @dragover.prevent @drop="drop(index)">
      <span class="drag-handle">⋮⋮</span>
      <template v-if="child.nodeType === 'PREDICATE'"><SemanticFieldSelector v-model="child.fieldCode" :fields="fields" @update:model-value="fieldChanged(child)" /><el-select v-model="child.operator" :disabled="!child.fieldCode" placeholder="选择判断方式" @change="operatorChanged(child)"><el-option v-for="option in operatorOptions(child)" :key="option.value" :label="option.label" :value="option.value" /></el-select><RuleValueEditor :field="fieldByCode(child.fieldCode)" :operator="child.operator" v-model="child.value" @update:model-value="emitUpdate" /><el-button link type="danger" @click="removeChild(index)">删除</el-button></template>
      <template v-else-if="child.nodeType === 'NOT'"><span class="not-label">不满足</span><ConditionGroupEditor :node="child.child" :fields="fields" :depth="depth+1" @remove="removeChild(index)" @update="emitUpdate" /></template>
      <ConditionGroupEditor v-else :node="child" :fields="fields" :depth="depth+1" @remove="removeChild(index)" @update="emitUpdate" />
    </div>
    <div class="rule-actions"><el-button link type="primary" @click="addPredicate">+ 添加条件</el-button><el-button link type="primary" @click="addGroup">+ 添加条件组</el-button><el-button link type="warning" @click="addNot">+ 添加 NOT</el-button></div>
  </div>
</template>
<script setup>
import SemanticFieldSelector from './SemanticFieldSelector.vue'
import RuleValueEditor from './RuleValueEditor.vue'
import { fieldByCode } from '@/idmp/utils/semanticField'
defineOptions({ name: 'ConditionGroupEditor' })
const props=defineProps({ node:{type:Object,required:true}, fields:{type:Array,default:()=>[]}, depth:{type:Number,default:0} }); const emit=defineEmits(['update','remove']); let movingIndex=-1
function fieldByCodeLocal(code){return fieldByCode(props.fields,code)}
function operatorOptions(condition){const kind=fieldByCodeLocal(condition.fieldCode)?.kind;if(kind==='DATETIME')return[{value:'BETWEEN',label:'在统计周期内'},{value:'GTE',label:'晚于或等于'},{value:'LTE',label:'早于或等于'}];if(kind==='NUMBER')return[{value:'EQ',label:'等于'},{value:'GT',label:'大于'},{value:'LT',label:'小于'}];if(kind==='VALUE_SET')return[{value:'IN_VALUE_SET',label:'属于值集'}];return[{value:'EQ',label:'等于'},{value:'IN',label:'属于'}]}
function fieldChanged(condition){condition.operator=operatorOptions(condition)[0]?.value||'EQ';condition.parameter=condition.operator==='BETWEEN'?'period':undefined;condition.value=condition.operator==='BETWEEN'?[]:'';emitUpdate()}
function operatorChanged(condition){condition.parameter=condition.operator==='BETWEEN'?'period':undefined;emitUpdate()} function emitUpdate(){emit('update')} function newPredicate(){return{id:`p-${Date.now()}-${Math.random()}`,nodeType:'PREDICATE',fieldCode:'',operator:'EQ',value:''}} function addPredicate(){props.node.children.push(newPredicate());emitUpdate()} function addGroup(){props.node.children.push({id:`g-${Date.now()}`,nodeType:'AND',children:[newPredicate()]});emitUpdate()} function addNot(){props.node.children.push({id:`n-${Date.now()}`,nodeType:'NOT',child:{id:`g-${Date.now()}`,nodeType:'AND',children:[newPredicate()]}});emitUpdate()} function removeChild(index){props.node.children.splice(index,1);emitUpdate()} function dragStart(index){movingIndex=index} function drop(index){if(movingIndex<0||movingIndex===index)return;const [item]=props.node.children.splice(movingIndex,1);props.node.children.splice(index,0,item);movingIndex=-1;emitUpdate()}
</script>
<style scoped>.rule-group{padding:14px;background:#fff;border:1px solid #e5e8ef;border-radius:8px}.rule-group.nested{margin-top:8px;background:#fafcff}.rule-group__head,.rule-row,.rule-actions{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.rule-group__head{justify-content:space-between;margin-bottom:10px;color:#262626;font-weight:600}.rule-row{padding:10px 8px;margin-top:8px;background:#f7f8fa;border-radius:6px}.rule-row :deep(.el-select),.rule-row :deep(.el-input){width:180px}.rule-row :deep(.el-date-editor){width:300px}.rule-empty{display:flex;align-items:flex-start;gap:10px;flex-wrap:wrap;padding:16px;background:#f7fbff;border:1px dashed #91caff;border-radius:6px;color:#595959}.rule-empty strong{color:#1677c2}.rule-empty span{flex:1;min-width:240px;line-height:22px}.drag-handle{color:#8c8c8c;cursor:grab}.not-label{color:#d46b08;font-weight:600}.rule-actions{margin-top:10px}</style>
