<template>
  <section class="chart-style-inspector" aria-label="组件可视化样式">
    <h3>主题方案</h3><p class="style-hint">应用协调的卡片、文字、边框与数据配色。</p><div class="style-presets"><button v-for="(preset, id) in presets" :key="id" type="button" :title="preset.label" @click="applyPreset(id)"><i v-for="color in presetSwatches(preset)" :key="color" :style="{ background: color }" />{{ preset.label }}</button></div>
    <KpiVariantPicker v-if="kind === 'kpi' && widget.type === 'kpi'" :model-value="kpiVariant" @update:model-value="patch({ kpiVariant: $event })" />
    <ChartPresentationPicker v-if="['bar', 'line', 'pie', 'scatter', 'radar', 'funnel', 'gauge', 'heatmap', 'map'].includes(kind)" :kind="kind" @select="applyPresentation" />
    <template v-if="isChart">
      <h3>图表</h3><template v-if="supportsPalette"><label>{{ paletteTitle }}<select :value="style.palettePreset" @change="patch({ palettePreset: $event.target.value })"><option value="default">默认</option><option value="medicalBlue">医疗蓝</option><option value="blueTeal">蓝青</option><option value="green">绿色</option><option value="warm">暖色</option><option value="colorful">多彩</option><option value="custom">自定义</option></select></label>
      <label>{{ paletteLabels[0] }}<input :aria-label="paletteLabels[0]" type="color" :value="paletteColors[0]" @input="setPaletteColor(0, $event.target.value)" /></label>
      <div v-if="style.palettePreset === 'custom'" class="palette-list"><label v-for="(_, index) in paletteColors" :key="index">{{ paletteLabels[index] }}<input type="color" :value="paletteColors[index]" @input="setPaletteColor(index, $event.target.value)" /></label></div></template>

      <template v-if="axisKinds"><h4>图例与坐标轴</h4><label><input type="checkbox" :checked="style.common.showLegend" @change="section('common', { showLegend: $event.target.checked })" />显示图例</label><label v-if="style.common.showLegend">位置<select :value="style.common.legendPosition" @change="section('common', { legendPosition: $event.target.value })"><option value="top">顶部</option><option value="bottom">底部</option></select></label><label>X 轴标签旋转<select :value="style.common.xAxisLabelRotation" @change="section('common', { xAxisLabelRotation: $event.target.value === 'auto' ? 'auto' : number($event.target.value) })"><option value="auto">自动</option><option v-for="value in [0,30,45,60,90]" :key="value" :value="value">{{ value }}°</option></select></label><label><input type="checkbox" :checked="style.common.showAxisLine" @change="section('common', { showAxisLine: $event.target.checked })" />显示轴线</label><label><input type="checkbox" :checked="style.common.showGridLine" @change="section('common', { showGridLine: $event.target.checked })" />显示网格线</label></template>
      <details class="style-advanced"><summary>高级</summary>

      <template v-if="kind === 'bar'"><h3>柱体</h3><label>透明度 <output>{{ percent(style.bar.opacity) }}%</output><input type="range" min="0" max="1" step="0.05" :value="style.bar.opacity" @input="section('bar', { opacity: number($event.target.value) })" /></label><label>圆角<select :value="style.bar.borderRadius" @change="section('bar', { borderRadius: number($event.target.value) })"><option :value="0">0</option><option :value="4">4</option><option :value="8">8</option><option :value="12">12</option></select></label><label>柱宽<select :value="style.bar.width" @change="section('bar', { width: $event.target.value })"><option value="auto">自动</option><option value="narrow">窄</option><option value="standard">标准</option><option value="wide">宽</option></select></label></template>

      <template v-if="kind === 'line'"><h3>线条</h3><label>宽度<select :value="style.line.width" @change="section('line', { width: number($event.target.value) })"><option v-for="value in [1,2,3,4,5]" :key="value" :value="value">{{ value }}</option></select></label><label>线型<select :value="style.line.type" @change="section('line', { type: $event.target.value })"><option value="solid">实线</option><option value="dashed">虚线</option><option value="dotted">点线</option></select></label><label>曲线<select :value="style.line.smooth ? 'smooth' : 'straight'" @change="section('line', { smooth: $event.target.value === 'smooth' })"><option value="straight">折线</option><option value="smooth">平滑曲线</option></select></label><h3>数据点</h3><label><input type="checkbox" :checked="style.line.showSymbol" @change="section('line', { showSymbol: $event.target.checked })" />显示数据点</label><template v-if="style.line.showSymbol"><label>形状<select :value="style.line.symbol" @change="section('line', { symbol: $event.target.value })"><option value="circle">圆形</option><option value="rect">方形</option><option value="diamond">菱形</option><option value="triangle">三角形</option></select></label><label>大小<select :value="style.line.symbolSize" @change="section('line', { symbolSize: number($event.target.value) })"><option v-for="value in [4,6,8,10,12]" :key="value" :value="value">{{ value }}</option></select></label></template><h3>面积</h3><label><input type="checkbox" :checked="style.line.area" @change="section('line', { area: $event.target.checked })" />面积填充</label><label v-if="style.line.area">透明度 <output>{{ percent(style.line.areaOpacity) }}%</output><input type="range" min="0" max="1" step="0.05" :value="style.line.areaOpacity" @input="section('line', { areaOpacity: number($event.target.value) })" /></label></template>

      <template v-if="kind === 'pie'"><h3>饼图</h3><label>形态<select :value="style.pie.donut ? 'donut' : 'pie'" @change="section('pie', { donut: $event.target.value === 'donut' })"><option value="pie">饼图</option><option value="donut">环形图</option></select></label><label v-if="style.pie.donut">中心孔<select :value="style.pie.innerRadius" @change="section('pie', { innerRadius: number($event.target.value) })"><option :value="40">40%</option><option :value="60">60%</option><option :value="75">75%</option></select></label><h3>标签</h3><label><input type="checkbox" :checked="style.pie.showLabel" @change="section('pie', { showLabel: $event.target.checked })" />显示标签</label><label v-if="style.pie.showLabel">位置<select :value="style.pie.labelPosition" @change="section('pie', { labelPosition: $event.target.value })"><option value="outside">外侧</option><option value="inside">内部</option></select></label></template>

      <template v-if="kind === 'scatter'"><h3>数据点</h3><label>形状<select :value="style.scatter.symbol" @change="section('scatter', { symbol: $event.target.value })"><option value="circle">圆形</option><option value="rect">方形</option><option value="diamond">菱形</option><option value="triangle">三角形</option></select></label><label>大小<select :value="style.scatter.symbolSize" @change="section('scatter', { symbolSize: number($event.target.value) })"><option v-for="value in [4,6,8,10,12]" :key="value" :value="value">{{ value }}</option></select></label><label>透明度 <output>{{ percent(style.scatter.opacity) }}%</output><input type="range" min="0" max="1" step="0.05" :value="style.scatter.opacity" @input="section('scatter', { opacity: number($event.target.value) })" /></label></template>
      <template v-if="kind === 'radar'"><h3>雷达图</h3><label>线条宽度<select :value="style.radar.width" @change="section('radar', { width: number($event.target.value) })"><option v-for="value in [1,2,3,4,5]" :key="value" :value="value">{{ value }}</option></select></label><label><input type="checkbox" :checked="style.radar.showSymbol" @change="section('radar', { showSymbol: $event.target.checked })" />显示数据点</label><label v-if="style.radar.showSymbol">数据点大小<select :value="style.radar.symbolSize" @change="section('radar', { symbolSize: number($event.target.value) })"><option v-for="value in [4,6,8,10,12]" :key="value" :value="value">{{ value }}</option></select></label><label><input type="checkbox" :checked="style.radar.area" @change="section('radar', { area: $event.target.checked })" />区域填充</label><label v-if="style.radar.area">填充透明度 <input type="range" min="0" max="1" step="0.05" :value="style.radar.areaOpacity" @input="section('radar', { areaOpacity: number($event.target.value) })" /></label></template>
      <template v-if="kind === 'funnel'"><h3>漏斗图</h3><label>分段间距<input type="number" min="0" max="20" :value="style.funnel.gap" @input="section('funnel', { gap: number($event.target.value) })" /></label><label><input type="checkbox" :checked="style.funnel.showLabel" @change="section('funnel', { showLabel: $event.target.checked })" />显示标签</label><label v-if="style.funnel.showLabel">标签位置<select :value="style.funnel.labelPosition" @change="section('funnel', { labelPosition: $event.target.value })"><option value="outside">外侧</option><option value="inside">内部</option></select></label></template>
      <template v-if="kind === 'heatmap'"><h3>热力图</h3><label>色带<select :value="style.heatmap.colorScale" @change="section('heatmap', { colorScale: $event.target.value })"><option value="blue">蓝色渐变</option><option value="blueTeal">蓝绿渐变</option><option value="green">绿色渐变</option><option value="warm">黄红渐变</option><option value="coolWarm">冷暖渐变</option></select></label><label>单元格边框<input type="color" :value="style.heatmap.borderColor" @input="section('heatmap', { borderColor: $event.target.value })" /></label><label>边框宽度<input type="number" min="0" max="5" :value="style.heatmap.borderWidth" @input="section('heatmap', { borderWidth: number($event.target.value) })" /></label></template>
      <template v-if="kind === 'gauge'"><h3>仪表盘</h3><label>进度颜色<input type="color" :value="style.gauge.progressColor || paletteColors[0]" @input="section('gauge', { progressColor: $event.target.value })" /></label><label>轨道颜色<input type="color" :value="style.gauge.trackColor" @input="section('gauge', { trackColor: $event.target.value })" /></label><label>数值颜色<input type="color" :value="style.gauge.valueColor || '#25343b'" @input="section('gauge', { valueColor: $event.target.value })" /></label><label><input type="checkbox" :checked="style.gauge.showPointer" @change="section('gauge', { showPointer: $event.target.checked })" />显示指针</label></template>
      <template v-if="kind === 'map'"><h3>区域配色</h3><label>低值颜色<input type="color" :value="style.map.lowColor" @input="section('map', { lowColor: $event.target.value })" /></label><label>高值颜色<input type="color" :value="style.map.highColor" @input="section('map', { highColor: $event.target.value })" /></label><label>边框颜色<input type="color" :value="style.map.borderColor" @input="section('map', { borderColor: $event.target.value })" /></label><label>边框宽度<input type="number" min="0" max="5" :value="style.map.borderWidth" @input="section('map', { borderWidth: number($event.target.value) })" /></label><label><input type="checkbox" :checked="style.map.showLabel" @change="section('map', { showLabel: $event.target.checked })" />显示区域名称</label></template>
      <template v-if="kind === 'table'"><h3>表格</h3><label>表头背景<input type="color" :value="style.table.headerBackground" @input="section('table', { headerBackground: $event.target.value })" /></label><label><input type="checkbox" :checked="style.table.zebra" @change="section('table', { zebra: $event.target.checked })" />斑马纹</label><label><input type="checkbox" :checked="style.table.compact" @change="section('table', { compact: $event.target.checked })" />紧凑模式</label></template>
      </details>
    </template>
    <template v-else-if="kind === 'kpi'"><h3>内容</h3><p v-if="widget.type === 'metric-group'" class="style-hint">设置组标题、指标标签、主值与比较信息使用的内容色调。</p><label>主数值颜色<input type="color" :value="style.kpi.valueColor || '#25343b'" @input="section('kpi', { valueColor: $event.target.value })" /></label><label>标题颜色<input type="color" :value="style.kpi.titleColor || '#52636c'" @input="section('kpi', { titleColor: $event.target.value })" /></label><label>趋势与比较颜色<input type="color" :value="style.kpi.trendColor || '#52636c'" @input="section('kpi', { trendColor: $event.target.value })" /></label></template>
    <button type="button" class="reset-visual-style" @click="$emit('reset')">恢复默认样式</button>
  </section>
</template>
<script setup>
import { computed } from 'vue'
import { applyWidgetStylePreset, chartPaletteLabels, resolveWidgetVisualStyle, WIDGET_STYLE_PRESETS, widgetPalette } from '../visualStyle.js'
import KpiVariantPicker from './KpiVariantPicker.vue'
import ChartPresentationPicker from './ChartPresentationPicker.vue'
import { applyChartPresentationPreset } from '../visualStyle.js'
import { normalizeKpiVariant } from '../kpiVariants.js'
const props = defineProps({ widget: { type: Object, required: true } })
const kind = computed(() => props.widget.type === 'metric-group' ? 'kpi' : props.widget.chartKind || props.widget.visualType || props.widget.type)
const isChart = computed(() => props.widget.type === 'chart')
const axisKinds = computed(() => ['line', 'bar', 'scatter', 'radar'].includes(kind.value))
const supportsPalette = computed(() => !['gauge', 'heatmap', 'map'].includes(kind.value))
const style = computed(() => resolveWidgetVisualStyle(props.widget))
const kpiVariant = computed(() => normalizeKpiVariant(props.widget.config?.style?.kpiVariant))
const presets = WIDGET_STYLE_PRESETS
const paletteColors = computed(() => { const colors = widgetPalette(props.widget); return [...colors, ...['#1261a6', '#4f8583', '#a47735', '#ab6680']].slice(0, 4) })
const paletteLabels = computed(() => chartPaletteLabels(props.widget, paletteColors.value.length))
const paletteTitle = computed(() => ({ pie: '分类配色', funnel: '阶段配色', heatmap: '数值色阶', map: '区域色阶', radar: '雷达系列配色' }[kind.value] || '数据配色'))
const emit = defineEmits(['update', 'reset'])
function number(value) { return Number(value) }
function percent(value) { return Math.round(Number(value) * 100) }
function patch(change) { emit('update', change) }
function section(name, change) { patch({ [name]: { ...style.value[name], ...change } }) }
function setPaletteColor(index, color) { const colors = [...paletteColors.value]; colors[index] = color; patch({ palettePreset: 'custom', colors }) }
function applyPreset(id) { emit('update', applyWidgetStylePreset(props.widget.config?.style, id)) }
function applyPresentation(id) { emit('update', applyChartPresentationPreset(props.widget, id)) }
function presetSwatches(preset) { return [preset.style.background, preset.style.kpi?.valueColor, preset.style.borderColor, (widgetPalette({ config: { style: preset.style } }) || [])[0]].filter(Boolean).slice(0, 4) }
</script>
<style scoped>
.chart-style-inspector { display:grid; gap:10px; padding-top:8px; }.chart-style-inspector h3 { margin:10px 0 0; font-size:12px; }.chart-style-inspector h4 { margin:2px 0 0; color:#52636c; font-size:11px; }.style-hint { margin:0; color:#78878e; font-size:11px; line-height:1.45; }.chart-style-inspector label { display:flex; align-items:center; justify-content:space-between; gap:8px; font-size:12px; }.chart-style-inspector select,.chart-style-inspector input[type=number] { width:110px; }.chart-style-inspector input[type=range] { width:110px; }.chart-style-inspector input[type=color] { width:42px; height:26px; padding:0; border:0; background:transparent; }.chart-style-inspector input[type=checkbox] { width:auto; margin-right:5px; }.style-presets { display:grid; grid-template-columns:repeat(2,minmax(0,1fr)); gap:5px; }.style-presets button { display:flex; align-items:center; gap:3px; min-width:0; padding:6px; overflow:hidden; color:#52636c; font-size:11px; text-overflow:ellipsis; white-space:nowrap; }.style-presets i { width:10px; height:10px; flex:0 0 auto; border:1px solid #d8e2e7; border-radius:2px; }.palette-list { display:grid; gap:6px; padding:7px; border:1px solid var(--db-border,#e3e9eb); border-radius:5px; }.style-advanced { display:grid; gap:8px; }.style-advanced summary { cursor:pointer; color:#52636c; font-size:12px; font-weight:600; }.reset-visual-style { margin-top:10px; padding:7px; border:1px solid var(--db-border,#e3e9eb); border-radius:5px; background:#fff; cursor:pointer; color:#52636c; }
</style>
