<template>
  <article class="dashboard-renderer-card db-kpi-card kpi-presentation" :class="[{ 'is-clickable': clickable }, `is-variant-${resolvedVariant}`]" @click="clickable && $emit('click')">
    <div class="kpi-presentation__head" :style="{ color: colors.title || undefined }"><span>{{ model.title || '指标' }}</span><span class="kpi-presentation__dot" :class="`is-${model.status || 'info'}`" /></div>
    <strong data-testid="binding-kpi-value" :style="{ color: colors.value || undefined }">{{ model.value || '暂无数据' }}<small v-if="model.unit">{{ model.unit }}</small></strong>
    <div v-if="model.change" class="kpi-presentation__change" :class="`is-${model.status || 'info'}`" :style="{ color: colors.trend || undefined }">{{ model.change }}</div>
    <div class="kpi-presentation__comparisons" :style="{ color: colors.trend || undefined }"><span>同比 {{ comparison(model.yoy, model.comparisonUnit || model.unit) }}</span><span>环比 {{ comparison(model.mom, model.comparisonUnit || model.unit) }}</span><b v-if="model.trendDirection" :aria-label="`趋势：${trendLabel}`">{{ trendArrow }}</b></div>
    <div v-if="model.target" class="kpi-presentation__target">{{ model.target }}</div>
  </article>
</template>

<script setup>
import { computed } from 'vue'
import { normalizeKpiVariant } from '../kpiVariants.js'
import { formatKpiComparison } from '../visualization.js'

const props = defineProps({ model: { type: Object, default: () => ({}) }, variant: { type: String, default: 'standard' }, colors: { type: Object, default: () => ({}) }, clickable: { type: Boolean, default: false } })
defineEmits(['click'])
const resolvedVariant = computed(() => normalizeKpiVariant(props.variant))
const comparison = formatKpiComparison
const trendArrow = computed(() => ({ up: '↑', down: '↓', flat: '↔' }[props.model.trendDirection] || '↔'))
const trendLabel = computed(() => ({ up: '上升', down: '下降', flat: '持平' }[props.model.trendDirection] || '持平'))
</script>

<style scoped>
.kpi-presentation { box-sizing:border-box; display:flex; flex-direction:column; width:100%; height:100%; min-height:0; padding:12px 14px; overflow:hidden; color:var(--db-text,#25343b); }.kpi-presentation.is-clickable { cursor:pointer; }.kpi-presentation__head { display:flex; justify-content:space-between; gap:8px; min-height:24px; font-size:13px; line-height:20px; }.kpi-presentation__head>span:first-child { overflow:hidden; text-overflow:ellipsis; white-space:nowrap; }.kpi-presentation__dot { flex:0 0 auto; width:8px; height:8px; margin-top:5px; border-radius:50%; background:#98a2b3; }.kpi-presentation__dot.is-success { background:var(--db-success,#357b62); }.kpi-presentation__dot.is-warning { background:var(--db-warning,#a47735); }.kpi-presentation__dot.is-danger { background:var(--db-danger,#b45858); }.kpi-presentation strong { display:block; margin:12px 0 8px; font-size:32px; font-weight:550; line-height:1.2; letter-spacing:-.6px; overflow-wrap:anywhere; font-variant-numeric:tabular-nums; }.kpi-presentation strong small { margin-left:3px; font-size:12px; font-weight:500; }.kpi-presentation__change { color:var(--db-secondary,#5c6d75); font-size:12px; }.kpi-presentation__change.is-success { color:var(--db-success,#357b62); }.kpi-presentation__change.is-danger { color:var(--db-danger,#b45858); }.kpi-presentation__comparisons { display:flex; align-items:center; gap:10px; margin-top:8px; color:var(--db-secondary,#5c6d75); font-size:11px; white-space:nowrap; }.kpi-presentation__comparisons b { margin-left:auto; font-size:18px; line-height:1; color:inherit; }.kpi-presentation__target { margin-top:6px; color:var(--db-muted,#78878e); font-size:11px; }
.kpi-presentation.is-variant-hero { padding:clamp(16px,3cqi,28px); justify-content:center; }.kpi-presentation.is-variant-hero strong { margin:10px 0; font-size:clamp(36px,8cqi,58px); font-weight:600; line-height:1.05; }.kpi-presentation.is-variant-hero .kpi-presentation__head { font-size:12px; }.kpi-presentation.is-variant-hero .kpi-presentation__target { display:none; }
.kpi-presentation.is-variant-horizontal { display:grid; grid-template-columns:minmax(0,1fr) auto auto; grid-template-rows:auto auto; column-gap:14px; align-items:center; padding:12px 16px; }.kpi-presentation.is-variant-horizontal .kpi-presentation__head { grid-column:1; grid-row:1 / span 2; }.kpi-presentation.is-variant-horizontal strong { grid-column:2; grid-row:1 / span 2; margin:0; font-size:clamp(24px,5cqi,36px); white-space:nowrap; }.kpi-presentation.is-variant-horizontal .kpi-presentation__change { grid-column:3; grid-row:1; white-space:nowrap; }.kpi-presentation.is-variant-horizontal .kpi-presentation__comparisons { grid-column:3; grid-row:2; margin:0; gap:4px; font-size:10px; }.kpi-presentation.is-variant-horizontal .kpi-presentation__comparisons b,.kpi-presentation.is-variant-horizontal .kpi-presentation__target { display:none; }
.kpi-presentation.is-variant-status { border-left:4px solid var(--db-border,#c8d5da); padding-left:16px; }.kpi-presentation.is-variant-status .kpi-presentation__dot { width:10px; height:10px; box-shadow:0 0 0 4px color-mix(in srgb,currentColor 12%,transparent); }.kpi-presentation.is-variant-status .kpi-presentation__head { padding-bottom:8px; border-bottom:1px solid var(--db-border,#e3e9eb); }.kpi-presentation.is-variant-status .kpi-presentation__comparisons { margin-top:auto; }.kpi-presentation.is-variant-status:has(.kpi-presentation__dot.is-danger) { border-left-color:var(--db-danger,#b45858); }.kpi-presentation.is-variant-status:has(.kpi-presentation__dot.is-warning) { border-left-color:var(--db-warning,#a47735); }.kpi-presentation.is-variant-status:has(.kpi-presentation__dot.is-success) { border-left-color:var(--db-success,#357b62); }
.kpi-presentation.is-variant-trend .kpi-presentation__change { display:none; }.kpi-presentation.is-variant-trend strong { margin-bottom:14px; }.kpi-presentation.is-variant-trend .kpi-presentation__comparisons { display:grid; grid-template-columns:1fr 1fr auto; gap:0; margin-top:auto; padding-top:10px; border-top:1px solid var(--db-border,#e3e9eb); }.kpi-presentation.is-variant-trend .kpi-presentation__comparisons span { padding-right:8px; }.kpi-presentation.is-variant-trend .kpi-presentation__comparisons span + span { padding-left:8px; border-left:1px solid var(--db-border,#e3e9eb); }.kpi-presentation.is-variant-trend .kpi-presentation__target { display:none; }
.kpi-presentation.is-variant-minimal { justify-content:center; padding:clamp(14px,3cqi,26px); }.kpi-presentation.is-variant-minimal .kpi-presentation__head { justify-content:center; min-height:auto; color:var(--db-muted,#78878e); font-size:11px; text-align:center; }.kpi-presentation.is-variant-minimal .kpi-presentation__dot,.kpi-presentation.is-variant-minimal .kpi-presentation__change,.kpi-presentation.is-variant-minimal .kpi-presentation__target { display:none; }.kpi-presentation.is-variant-minimal strong { margin:10px 0 0; font-size:clamp(34px,7cqi,54px); font-weight:500; line-height:1.05; text-align:center; }.kpi-presentation.is-variant-minimal .kpi-presentation__comparisons { justify-content:center; margin-top:10px; font-size:10px; }.kpi-presentation.is-variant-minimal .kpi-presentation__comparisons b { display:none; }
@container (max-height:150px) { .kpi-presentation { padding:10px 12px; }.kpi-presentation strong { font-size:28px; margin:6px 0; }.kpi-presentation__target { display:none; } }
@container (max-height:105px) { .kpi-presentation { justify-content:center; padding:6px 9px; }.kpi-presentation__head { min-height:18px; font-size:11px; line-height:16px; }.kpi-presentation strong { margin:3px 0 0; font-size:22px; line-height:1; }.kpi-presentation__change,.kpi-presentation__comparisons,.kpi-presentation__target { display:none !important; } }
@container (max-width:330px) { .kpi-presentation.is-variant-horizontal { display:flex; flex-wrap:wrap; align-content:center; gap:4px 8px; }.kpi-presentation.is-variant-horizontal .kpi-presentation__head { width:100%; }.kpi-presentation.is-variant-horizontal strong,.kpi-presentation.is-variant-horizontal .kpi-presentation__change,.kpi-presentation.is-variant-horizontal .kpi-presentation__comparisons { display:block; }.kpi-presentation.is-variant-horizontal .kpi-presentation__comparisons { margin-left:auto; }.kpi-presentation.is-variant-hero strong,.kpi-presentation.is-variant-minimal strong { font-size:30px; } }
</style>
